import "dotenv/config";
import ws from "ws";
import { neonConfig } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "../src/generated/prisma";

neonConfig.webSocketConstructor = ws;

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const sources = [
  {
    slug: "guernica",
    title: "Guernica",
    year: 1937,
    nature: "Peinture à l'huile sur toile",
    author: "Pablo Picasso",
    origin: "Commande du gouvernement républicain espagnol ; Musée Reina Sofía, Madrid",
    description: "Œuvre monumentale dénonçant le bombardement de la ville basque de Guernica par les forces fascistes allemandes et italiennes durant la guerre civile espagnole.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/74/PicassoGuernica.jpg",
    color: "#B03030",
    nasdiN: "Guernica est une peinture à l'huile sur toile de très grand format (349 × 776 cm), réalisée entièrement en noir, blanc et gris. Ce choix monochrome rappelle délibérément le rendu des photographies de presse et des images d'actualité de l'époque, ancrant l'œuvre dans une réalité documentaire immédiate. Le style cubiste, fragmenté et expressionniste, disloque les corps et les formes pour traduire visuellement la violence et le chaos du bombardement.",
    nasdiA: "Pablo Picasso (1881-1973), peintre espagnol d'avant-garde et figure majeure du cubisme, est alors au sommet de sa renommée internationale. Engagé politiquement à gauche, il est directeur honoraire du musée du Prado et deviendra membre du Parti communiste espagnol en 1944. Son statut lui confère une plateforme mondiale unique pour témoigner des horreurs de la guerre civile espagnole.",
    nasdiS: "L'œuvre est commandée par le gouvernement républicain espagnol pour représenter l'Espagne à l'Exposition internationale des Arts et Techniques dans la Vie moderne de Paris (1937). Elle est exposée dans le pavillon espagnol avant de parcourir l'Europe et les États-Unis pour sensibiliser l'opinion internationale au sort de l'Espagne. Conservée au MoMA de New York jusqu'en 1981, elle est ensuite rapatriée en Espagne après la mort de Franco.",
    nasdiD: "Peinte entre mai et juin 1937, Guernica est une réaction directe et immédiate au bombardement de la ville de Guernica le 26 avril 1937 — une opération menée par la légion Condor nazie à la demande de Franco, qui fit des centaines de victimes civiles. La rapidité d'exécution témoigne de l'urgence et de la colère de l'artiste face à cette attaque contre une population sans défense.",
    nasdiI: "Guernica dénonce la barbarie de la guerre moderne et de la violence totalitaire contre les populations civiles. À travers un langage visuel fragmenté — corps disloqués, animaux en agonie, cri de douleur, ampoule électrique en forme d'œil — Picasso transforme un événement local en symbole universel de la souffrance humaine causée par les conflits armés. L'œuvre est aujourd'hui l'un des anti-monuments de guerre les plus puissants jamais créés.",
  },
  {
    slug: "liberte-guidant-le-peuple",
    title: "La Liberté guidant le peuple",
    year: 1830,
    nature: "Peinture à l'huile sur toile",
    author: "Eugène Delacroix",
    origin: "Musée du Louvre, Paris",
    description: "Allégorie romantique des Trois Glorieuses de juillet 1830, représentant la Liberté personnifiée guidant le peuple parisien insurgé, drapeau tricolore à la main.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg",
    color: "#B03030",
    nasdiN: "Grande peinture à l'huile sur toile (260 × 325 cm), de style romantique. L'œuvre mêle scène historique et allégorie, combinant personnages réels (bourgeois en chapeau haut-de-forme, artisan, gamin de Paris) et figure symbolique (la Liberté portant le drapeau tricolore, seins nus). La composition en triangle ascendant, avec la Liberté au sommet, donne au tableau une puissante dynamique ascensionnelle.",
    nasdiA: "Eugène Delacroix (1798-1863), chef de file du romantisme français, est lui-même un témoin des journées insurrectionnelles. Bien qu'issu de la bourgeoisie et non d'un milieu combattant, il est profondément marqué par les événements et écrit dans une lettre : 'Si je n'ai pas combattu pour la patrie, au moins je peindrai pour elle.' Son regard de témoin engagé confère au tableau une émotion authentique.",
    nasdiS: "Présentée au Salon de 1831 avec un accueil mitigé, l'œuvre est achetée par l'État mais jugée trop subversive pour être exposée longtemps. Elle disparaît temporairement des salles du Louvre avant d'y être réinstallée de façon permanente. Sa résonance symbolique traverse les siècles — on retrouve sa figure sur l'ancienne pièce de 100 francs français et elle inspire de nombreuses représentations de la République française.",
    nasdiD: "Peinte en 1830, quelques mois après les Trois Glorieuses (27-29 juillet 1830) qui renversent Charles X et installent Louis-Philippe sur le trône. Ce contexte de révolution libérale, portée principalement par la bourgeoisie parisienne, explique la présence du bourgeois au chapeau haut-de-forme aux côtés des combattants populaires. Delacroix célèbre autant un idéal de liberté qu'un événement historique récent.",
    nasdiI: "L'œuvre proclame le triomphe du peuple uni — toutes classes confondues — au nom des idéaux de liberté hérités de 1789. La Liberté, baïonnette à la main, incarne une République combattante qui n'hésite pas à prendre les armes pour ses droits. Le tableau est devenu l'une des icônes mondiales de la lutte pour la démocratie, universellement reconnaissable comme symbole de la France révolutionnaire.",
  },
  {
    slug: "les-sabines",
    title: "L'Enlèvement des Sabines",
    year: 1799,
    nature: "Peinture à l'huile sur toile",
    author: "Jacques-Louis David",
    origin: "Musée du Louvre, Paris",
    description: "Scène épique de la Rome antique montrant les femmes sabines s'interposant entre leurs pères et leurs maris romains, symbole de réconciliation nationale après les déchirements révolutionnaires.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Jacques-Louis_David_-_Intervention_of_the_Sabine_Women_-_Google_Art_Project.jpg",
    color: "#B03030",
    nasdiN: "Très grande composition néoclassique à l'huile sur toile (385 × 522 cm). David choisit délibérément le moment de la réconciliation — les femmes sabines s'interposant entre les combattants — plutôt que l'enlèvement lui-même, représenté par ses prédécesseurs. Cette décision narrative transforme une scène de violence en appel à la paix, amplifié par la nudité des guerriers qui renforce l'aspect symbolique sur le réalisme historique.",
    nasdiA: "Jacques-Louis David (1748-1825) est le peintre officiel de la Révolution et de l'Empire, auteur du Serment du Jeu de Paume et de La Mort de Marat. Emprisonné après Thermidor pour son soutien à Robespierre, il peint cette œuvre lors de sa détention. Elle est donc une méditation personnelle sur la réconciliation nationale, dans laquelle il met en scène ses propres angoisses politiques et son désir de sortir des vengeances révolutionnaires.",
    nasdiS: "Exposée publiquement dans le Salon Carré du Louvre de 1799 à 1804, l'œuvre est l'une des premières en France à être montrée contre un droit d'entrée payant, attirant des dizaines de milliers de visiteurs. David présente l'œuvre accompagnée d'une explication écrite détaillée de ses intentions, inaugurant une nouvelle forme de médiation culturelle entre l'artiste et son public.",
    nasdiD: "Peinte entre 1796 et 1799, en pleine période du Directoire, après les années de Terreur qui ont vu des milliers d'exécutions et des familles déchirées entre différentes factions révolutionnaires. Le sujet — des femmes s'interposant entre des combattants qui sont à la fois leurs pères et leurs maris — est une métaphore transparente de la nécessité de réconcilier royalistes et républicains dans une France épuisée par ses propres contradictions.",
    nasdiI: "À travers ce récit romain, David plaide pour la réconciliation nationale après les violences révolutionnaires. Les femmes Sabines — devenues épouses romaines après l'enlèvement — représentent les Français qui ont des loyautés dans les deux camps et refusent de choisir entre leur famille d'origine et leur famille adoptive. L'œuvre est un appel solennel à dépasser les vengeances politiques et à reconstruire l'unité nationale sur les ruines de la Terreur.",
  },
  {
    slug: "radeau-de-la-meduse",
    title: "Le Radeau de la Méduse",
    year: 1819,
    nature: "Peinture à l'huile sur toile",
    author: "Théodore Géricault",
    origin: "Musée du Louvre, Paris",
    description: "Représentation dramatique du naufrage de la frégate Méduse en 1816, symbole de l'incompétence et de l'injustice du régime de la Restauration qui place la loyauté politique avant la compétence.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg",
    color: "#B03030",
    nasdiN: "Peinture à l'huile sur toile de très grand format (491 × 716 cm), de style romantique. Géricault représente l'instant précis où les survivants, entassés sur un radeau de fortune après 13 jours de dérive, aperçoivent à l'horizon le navire Argus qui viendra les secourir. La composition pyramidale, des morts au premier plan aux survivants qui agitent les bras, traduit visuellement l'oscillation entre désespoir et espoir.",
    nasdiA: "Théodore Géricault (1791-1824) est un jeune peintre romantique qui n'a pas vécu le naufrage directement. Pour atteindre la vérité documentaire, il rencontre des rescapés, lit leurs témoignages (notamment le récit de Savigny et Corréard), et réalise des études de cadavres et de membres amputés à l'hôpital Beaujon. Cette obsession de la réalité anatomique, au service d'un propos politique, est caractéristique du romantisme engagé.",
    nasdiS: "Présentée au Salon de 1819, l'œuvre provoque un scandale politique retentissant : le naufrage de la Méduse (juillet 1816) avait été causé par l'incompétence d'un capitaine royaliste nommé par favoritisme sous la Restauration. Les 147 naufragés laissés sur le radeau avaient subi 13 jours de terreur, de violence et de cannibalisme. L'œuvre est acquise par le Louvre en 1824, juste après la mort de Géricault à 32 ans.",
    nasdiD: "Peinte en 1818-1819, trois ans après le naufrage (juillet 1816) qui fit 147 naufragés sur le radeau — dont seulement 15 survécurent. Le contexte est celui de la Restauration (retour des Bourbons depuis 1815), régime que Géricault et ses contemporains libéraux rejettent. La nomination du capitaine incompétent Hugues Duroy de Chaumareys par favoritisme politique est au cœur du scandale.",
    nasdiI: "L'œuvre dénonce les dérives d'un système politique qui place la loyauté au régime avant la compétence, avec des conséquences mortelles pour les citoyens ordinaires. Au-delà du fait divers, Géricault signe une critique radicale de la Restauration et de ses injustices sociales. Il inaugure ainsi l'art romantique comme arme politique, ouvrant la voie à Delacroix et à toute une génération de peintres engagés.",
  },
  {
    slug: "vercingetorix-devant-cesar",
    title: "Vercingétorix jette ses armes aux pieds de César",
    year: 1899,
    nature: "Peinture académique à l'huile sur toile",
    author: "Lionel Royer",
    origin: "Musée Crozatier, Le Puy-en-Velay",
    description: "Représentation romantique et nationaliste de la reddition de Vercingétorix après la bataille d'Alésia (-52), œuvre fondatrice du mythe 'nos ancêtres les Gaulois' diffusé dans les manuels scolaires de la IIIe République.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Vercingetorix_throws_down_his_arms_at_the_feet_of_Julius_Caesar.jpg",
    color: "#B03030",
    nasdiN: "Grande peinture académique et nationaliste (321 × 482 cm) à l'huile sur toile. Le tableau représente un moment légendaire de l'histoire de France : la reddition du chef gaulois Vercingétorix devant Jules César après la bataille d'Alésia (-52 av. J.-C.). La mise en scène théâtrale — Vercingétorix sur son cheval, lançant son épée aux pieds de César immobile — favorise l'exaltation des sentiments patriotiques au détriment de la rigueur historique.",
    nasdiA: "Lionel Royer (1852-1926) est un peintre académique français, formé aux Beaux-Arts de Paris. Son tableau est une commande de l'État français, dans le cadre d'une politique culturelle délibérée de construction de l'identité nationale. Royer n'est pas un témoin mais un interprète du mythe national gaulois, deux mille ans après les événements qu'il représente.",
    nasdiS: "Exposé au Salon de 1899 puis largement reproduit dans les manuels scolaires de la IIIe République, le tableau participe massivement à la diffusion du mythe 'nos ancêtres les Gaulois'. Il contribue à forger une identité nationale autour de la figure de Vercingétorix comme premier héros national français — un choix politique autant qu'historique, dans une France cherchant à surmonter la défaite de 1870.",
    nasdiD: "Peint en 1899, soit 1 951 ans après les événements qu'il représente (-52 av. J.-C.). Le contexte de la IIIe République, marqué par la nécessité de reconstruire l'identité nationale après la défaite humiliante face à la Prusse (1870-1871) et la perte de l'Alsace-Lorraine, explique le choix de ce sujet exaltant la résistance héroïque face à l'envahisseur, même dans la défaite.",
    nasdiI: "Le tableau construit un récit national centré sur la noblesse de la défaite et la grandeur du sacrifice : Vercingétorix se livre pour épargner son peuple, préférant sa propre captivité au massacre de ses hommes. Ce mythe fondateur, diffusé dans toutes les écoles républicaines, vise à unifier la nation française autour d'ancêtres communs et à alimenter le sentiment patriotique dans une France humiliée par la défaite de 1870. Il illustre aussi comment l'histoire peut être instrumentalisée par le politique.",
  },
  {
    slug: "declaration-droits-homme",
    title: "Déclaration des droits de l'homme et du citoyen",
    year: 1789,
    nature: "Texte officiel",
    author: "Assemblée nationale constituante",
    origin: "Assemblée nationale, Versailles ; Archives nationales, Paris",
    description: "Texte fondateur de la Révolution française proclamant les droits naturels et imprescriptibles de l'homme, posant les bases de la conception moderne des libertés individuelles et de la souveraineté nationale.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Declaration_of_the_Rights_of_Man_and_of_the_Citizen_in_1789.jpg",
    color: "#B03030",
    nasdiN: "Document officiel de 17 articles, rédigé par l'Assemblée nationale constituante en français juridique. Il s'inspire des philosophies des Lumières (Rousseau, Locke, Montesquieu) et de la Déclaration d'indépendance américaine (1776). Sa structure est à la fois juridique, philosophique et politique : chaque article pose un principe universel applicable à tout être humain, indépendamment de sa nationalité ou de sa condition.",
    nasdiA: "L'Assemblée nationale constituante, composée de représentants du Tiers-État, de la noblesse libérale et du clergé progressiste. Parmi les rédacteurs influents : La Fayette (qui s'inspira des suggestions de Jefferson), l'abbé Sieyès (auteur de 'Qu'est-ce que le Tiers-État ?') et Mirabeau. Ce texte est une œuvre collective émergeant d'un moment révolutionnaire sans précédent dans l'histoire française.",
    nasdiS: "Adoptée le 26 août 1789 et intégrée comme préambule de la Constitution de 1791, cette déclaration est affichée et diffusée dans toute la France révolutionnaire. Traduite dans de nombreuses langues, elle inspire les révolutions libérales du XIXe siècle (1830, 1848) et constitue la base philosophique de la Déclaration universelle des droits de l'homme adoptée par l'ONU en 1948. Elle figure toujours dans le bloc de constitutionnalité français.",
    nasdiD: "Rédigée en août 1789, en plein cœur de la Révolution française, quelques semaines après la prise de la Bastille (14 juillet) et à la suite de la nuit du 4 août qui abolit les privilèges féodaux. Ce contexte d'effervescence révolutionnaire, combiné à l'influence des penseurs des Lumières et de l'exemple américain, explique l'ambition universaliste et le ton philosophique du texte, au-delà du simple document politique.",
    nasdiI: "La Déclaration affirme que les droits naturels de l'homme — liberté, égalité, propriété, sûreté, résistance à l'oppression — sont antérieurs et supérieurs à toute loi. Elle place la souveraineté dans la Nation et non dans le roi, renversant le fondement de l'Ancien Régime. Son article 1er ('Les hommes naissent et demeurent libres et égaux en droits') reste l'une des formulations les plus influentes de l'histoire politique mondiale.",
  },
  {
    slug: "code-hammourabi",
    title: "Code d'Hammourabi",
    year: -1754,
    nature: "Stèle gravée (basalte noir)",
    author: "Hammourabi, roi de Babylone",
    origin: "Babylone, Mésopotamie ; Musée du Louvre, Paris (depuis 1902)",
    description: "L'un des plus anciens codes de lois écrits de l'humanité, gravé sur une stèle de basalte noir de 2,25 mètres, fixant 282 lois couvrant la vie sociale, économique et pénale de Babylone.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Code_of_Hammurabi_2.jpg/800px-Code_of_Hammurabi_2.jpg",
    color: "#C8902A",
    nasdiN: "Stèle de basalte noir de 2,25 mètres de hauteur, surmontée d'un bas-relief représentant Hammourabi debout devant le dieu soleil Shamash qui lui remet les lois. Les 282 lois sont gravées en écriture cunéiforme akkadienne sur toute la surface de la stèle, organisées par thèmes (commerce, famille, propriété, droit pénal, droit du travail). C'est un objet à la fois juridique, religieux et politique, conçu pour être exposé publiquement.",
    nasdiA: "Hammourabi (règne : -1792 à -1750), sixième roi de la Première Dynastie babylonienne, a unifié la Mésopotamie sous sa domination après de nombreuses guerres de conquête. En se faisant représenter recevant les lois du dieu soleil Shamash — dieu de la justice — il confère à son code une autorité divine, légitimant ainsi son pouvoir politique par une dimension sacrée et immuable. C'est un souverain qui comprend que la loi est aussi un outil de propagande.",
    nasdiS: "Découverte en 1901-1902 à Suse (Iran actuel) par une mission archéologique française dirigée par Jacques de Morgan, la stèle avait été emportée par le roi élamite Shutruk-Nahhunte vers -1200 comme butin de guerre. Elle est exposée depuis 1902 au Louvre, où elle constitue l'une des pièces maîtresses. En son temps, des copies sur argile étaient probablement diffusées dans tout l'empire pour informer les juges et les sujets.",
    nasdiD: "Rédigé vers -1754, au temps de l'apogée de l'empire babylonien sous Hammourabi. Ce code intervient après une longue période de guerres et de réunification de la Mésopotamie : il vise à unifier sous une même loi des peuples de traditions juridiques différentes, à garantir la stabilité sociale nécessaire au commerce et à l'agriculture, et à légitimer le pouvoir du roi comme garant de la justice divine.",
    nasdiI: "Le Code d'Hammourabi pose le principe fondateur que le fort ne doit pas écraser le faible, et établit un système de droits et de peines proportionnées selon le principe du talion ('œil pour œil, dent pour dent'). Il est l'un des premiers témoignages de l'idée que le pouvoir doit être encadré par des règles écrites, connues de tous et non soumises à l'arbitraire du prince. Ce principe — la primauté de la loi — est la base de tout État de droit moderne.",
  },
  {
    slug: "magna-carta",
    title: "Magna Carta",
    year: 1215,
    nature: "Charte royale",
    author: "Roi Jean d'Angleterre et barons anglais",
    origin: "Runnymede, Angleterre ; British Library et Salisbury Cathedral",
    description: "Charte des libertés signée sous la contrainte par le roi Jean sans Terre, limitant pour la première fois le pouvoir royal et posant les bases du droit constitutionnel anglais et de l'État de droit.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg",
    color: "#7B4F9E",
    nasdiN: "Document royal (charte) rédigé en latin médiéval, scellé de cire et non signé au sens moderne. Il comprend 63 clauses protégeant les droits des barons, de l'Église et, partiellement, des hommes libres. Sa nature est hybride : accord de paix entre le roi et ses vassaux révoltés, mais aussi proto-constitution limitant le pouvoir royal par des règles écrites que même le souverain ne peut violer.",
    nasdiA: "Le roi Jean d'Angleterre (dit 'Jean sans Terre', 1166-1216), contraint par une coalition de barons révoltés qui ont pris Londres. Le document est co-rédigé par les barons et l'archevêque de Canterbury Stephen Langton, médiateur essentiel dans les négociations. La rédaction sous la contrainte — Jean la répudia dès que le pape Innocent III l'annula — lui confère un caractère de conquête arrachée par la force plutôt que de concession royale volontaire.",
    nasdiS: "Scellée à Runnymede le 15 juin 1215, la Magna Carta est annulée par le pape Innocent III quelques mois plus tard mais réémise plusieurs fois sous des formes modifiées au cours du XIIIe siècle. Ses principes — notamment l'habeas corpus (clause 39) et l'interdiction de lever des impôts sans consentement — deviennent fondamentaux dans le droit anglais et inspirent directement la Constitution américaine et la Déclaration universelle des droits de l'homme.",
    nasdiD: "Rédigée en juin 1215, dans un contexte de crise politique majeure : Jean sans Terre a perdu la Normandie face à la France (1204), imposé des taxes excessives pour financer ses guerres, et s'est aliéné à la fois les barons et l'Église. La révolte baronniale de 1215 le contraint à négocier depuis une position de faiblesse totale. Ce moment de vulnérabilité royale est fondateur : il montre que même un roi peut être contraint de respecter des règles.",
    nasdiI: "La Magna Carta établit pour la première fois le principe que le pouvoir du roi est limité par la loi, et non au-dessus d'elle. Sa clause 39 — 'Aucun homme libre ne sera arrêté, emprisonné [...] si ce n'est par le jugement légal de ses pairs ou par la loi du pays' — fonde le principe d'habeas corpus et de présomption d'innocence. Elle est la pierre fondatrice de l'État de droit occidental et de la tradition constitutionnelle libérale.",
  },
  {
    slug: "tank-man",
    title: "Tank Man, place Tiananmen",
    year: 1989,
    nature: "Photographie de presse",
    author: "Jeff Widener (Associated Press)",
    origin: "Place Tiananmen, Pékin, Chine ; 5 juin 1989",
    description: "Cliché iconique d'un homme seul face à une colonne de chars au lendemain de la répression de la place Tiananmen, symbole mondial de la résistance individuelle face aux régimes autoritaires.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/3/38/Tianasquare.jpg",
    color: "#B03030",
    nasdiN: "Photographie en couleur prise au téléobjectif (400mm) depuis la fenêtre du Beijing Hotel, le 5 juin 1989, à environ 800 mètres de distance. L'image capture un homme ordinaire, non identifié, arrêtant une colonne de chars de type Type 59 par sa seule présence physique. Sa composition simple — figure humaine solitaire face à la puissance mécanique écrasante — lui confère une force symbolique universelle immédiatement lisible.",
    nasdiA: "Jeff Widener, photographe de l'Associated Press, prend le cliché depuis sa chambre d'hôtel, lui-même malade d'une intoxication alimentaire et blessé à la tête par un projectile lors des manifestations. D'autres photographes (Stuart Franklin du Magnum, Charlie Cole du Newsweek) capturent la même scène sous des angles légèrement différents. L'identité de l'homme reste inconnue à ce jour — il n'a jamais été retrouvé.",
    nasdiS: "Les pellicules sont clandestinement dissimulées dans les sous-vêtements des photographes pour franchir les contrôles de l'armée chinoise. L'image est diffusée mondialement par l'Associated Press le 5 juin 1989 et paraît en une de dizaines de quotidiens internationaux le lendemain. Elle est aujourd'hui intégralement censurée en Chine, où sa simple possession peut entraîner des poursuites. Time Magazine l'a classée parmi les 100 photographies les plus influentes de l'histoire.",
    nasdiD: "Prise le 5 juin 1989, au lendemain de la répression violente du mouvement étudiant pro-démocratie de la place Tiananmen par l'armée chinoise (nuit du 3 au 4 juin), qui fit des centaines à des milliers de morts selon les estimations — le bilan exact reste classifié par Pékin. Le contexte mondial — fin de la Guerre froide, chute imminente du mur de Berlin en novembre 1989 — donne à cette image une résonance planétaire exceptionnelle.",
    nasdiI: "L'image symbolise avec une puissance rare la résistance du courage individuel désarmé face à la violence d'État mécanisée. L'anonymat total de l'homme — dont le destin reste incertain — universalise le symbole au-delà du contexte chinois : il pourrait être n'importe quel citoyen refusant l'injustice. Elle pose aussi la question de la puissance des images dans les régimes autoritaires, qui tentent de les effacer précisément parce qu'elles sont indestructibles.",
  },
  {
    slug: "traite-versailles",
    title: "Traité de Versailles",
    year: 1919,
    nature: "Traité international",
    author: "Puissances alliées et associées / Délégation allemande",
    origin: "Galerie des Glaces, château de Versailles, France",
    description: "Traité de paix mettant fin à la Première Guerre mondiale, imposant à l'Allemagne de lourdes réparations et des amputations territoriales, et semant les germes de la montée du nazisme.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/thirty/Signatories_of_Versailles_Peace_Treaty,_1919.jpg",
    color: "#B03030",
    nasdiN: "Document diplomatique de 440 articles répartis en 15 parties, rédigé en français et en anglais — les deux seules langues officielles de la conférence, excluant l'allemand. Il comprend le pacte de la Société des Nations, les dispositions territoriales, militaires (limitation de l'armée à 100 000 hommes) et économiques (réparations) imposées à l'Allemagne. Sa longueur et sa complexité reflètent l'ambition de réorganiser l'ordre mondial entier.",
    nasdiA: "Négocié par les 'Quatre Grands' : Woodrow Wilson (États-Unis, partisan des '14 Points'), Georges Clemenceau (France, déterminé à maximiser les garanties de sécurité), David Lloyd George (Royaume-Uni, position intermédiaire) et Vittorio Orlando (Italie, déçue de ses gains). L'Allemagne est totalement exclue des négociations et contrainte de signer un texte qu'elle juge humiliant — notamment l'article 231, la controversée 'clause de culpabilité de guerre'.",
    nasdiS: "Signé le 28 juin 1919 dans la Galerie des Glaces du château de Versailles — lieu symbolique où avait été proclamé l'Empire allemand en 1871, après la victoire prussienne sur la France. Cette mise en scène revancharde délibérée est un affront calculé. Le traité est immédiatement perçu en Allemagne comme un 'Diktat' humiliant, contribuant à l'instabilité de la République de Weimar et à la popularité des mouvements nationalistes radicaux.",
    nasdiD: "Signé le 28 juin 1919, cinq ans jour pour jour après l'assassinat de l'archiduc François-Ferdinand à Sarajevo (28 juin 1914), événement déclencheur de la guerre. Le contexte est celui d'une Europe dévastée (10 millions de morts militaires, 7 millions de civils) et d'une France traumatisée qui exige des garanties maximales. Les négociateurs ignorent alors les avertissements de l'économiste John Maynard Keynes sur les effets destructeurs d'un traité trop punitif.",
    nasdiI: "Le Traité impose à l'Allemagne la responsabilité exclusive de la guerre (article 231), des réparations colossales (132 milliards de marks-or, dont le dernier versement sera effectué en 2010), des amputations territoriales majeures et une limitation militaire sévère. L'humiliation ressentie par les Allemands nourrira le ressentiment nationaliste, affaiblira la démocratie de Weimar et facilitera la montée d'Hitler, qui en fera sa cible rhétorique principale — faisant de ce traité l'une des causes directes de la Seconde Guerre mondiale.",
  },
  {
    slug: "edit-nantes",
    title: "Édit de Nantes",
    year: 1598,
    nature: "Édit royal",
    author: "Henri IV, roi de France",
    origin: "Château de Nantes ; Archives nationales, Paris",
    description: "Édit accordant la liberté de conscience et de culte aux protestants français, mettant fin aux guerres de Religion qui ravageaient la France depuis 1562, précurseur fragile de la liberté religieuse moderne.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/37/Edict_of_Nantes-1598.jpg",
    color: "#7B4F9E",
    nasdiN: "Document royal de 92 articles généraux, 56 articles particuliers et 2 brevets secrets, rédigé en français juridique. Il s'agit d'un édit de pacification qui accorde aux protestants non seulement la liberté de conscience et de culte dans des lieux définis, mais aussi des places de sûreté militaires (villes fortifiées) et des tribunaux spéciaux bi-confessionnels (chambres mi-parties). C'est un texte politique et pragmatique autant que religieux.",
    nasdiA: "Henri IV (1553-1610), roi de France né protestant sous le nom d'Henri de Navarre, converti au catholicisme en 1593 pour accéder au trône ('Paris vaut bien une messe'). Son parcours personnel exceptionnel — ayant vécu dans les deux camps — le rend particulièrement capable de comprendre les deux confessions. Il voit dans cet édit un instrument de reconstruction nationale pragmatique plutôt qu'un idéal de tolérance philosophique.",
    nasdiS: "Promulgué à Nantes en avril 1598, l'édit est immédiatement contesté par les parlements et l'Église catholique qui doivent être contraints de l'enregistrer. Sa révocation par Louis XIV en 1685 (Édit de Fontainebleau) provoque l'exode de 200 000 à 400 000 protestants — artisans, marchands, officiers — affaiblissant durablement l'économie française et enrichissant la Prusse, les Pays-Bas et l'Angleterre qui les accueillent.",
    nasdiD: "Promulgué en 1598, après 36 ans de guerres de Religion (1562-1598) qui ont ravagé la France dans huit conflits distincts, culminant avec le massacre de la Saint-Barthélemy (août 1572, 3 000 à 30 000 morts selon les estimations). La victoire d'Henri IV sur la Ligue catholique et sur l'Espagne lui permet enfin d'imposer cette paix dans un royaume épuisé, saigné par des décennies de violence fratricide.",
    nasdiI: "L'Édit de Nantes pose pour la première fois en France le principe qu'un État peut contenir des sujets de confessions différentes sans que cela mette en péril son unité politique. En distinguant la foi privée de la loyauté politique au souverain, il innove profondément dans la conception du rapport entre religion et pouvoir. Bien que révoqué, il reste un précurseur fondateur de la liberté de conscience et de la séparation entre appartenance religieuse et citoyenneté.",
  },
  {
    slug: "appel-18-juin",
    title: "L'Appel du 18 juin",
    year: 1940,
    nature: "Discours radiodiffusé",
    author: "Général Charles de Gaulle",
    origin: "Studios de la BBC, Londres ; 18 juin 1940",
    description: "Discours prononcé par de Gaulle sur les ondes de la BBC depuis Londres, appelant les Français à poursuivre le combat après la demande d'armistice de Pétain, acte fondateur de la Résistance française.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/De_Gaulle_au_microphone_%28cropped%29.jpg/800px-De_Gaulle_au_microphone_%28cropped%29.jpg",
    color: "#B03030",
    nasdiN: "Discours radiodiffusé d'environ 5 minutes, prononcé en français depuis les studios londoniens de la BBC le 18 juin 1940. Il n'a pas été enregistré par la BBC lors de sa première diffusion, et le texte connu est une retranscription légèrement différente de la version réenregistrée le 22 juin. C'est un document sonore dont la portée est davantage symbolique que documentaire : sa signification a été construite et amplifiée a posteriori par la mémoire nationale.",
    nasdiA: "Charles de Gaulle (1890-1970), général de brigade à titre temporaire et sous-secrétaire d'État à la Guerre dans le gouvernement Reynaud, s'exprime sans aucun mandat officiel — le gouvernement Pétain vient de prendre le pouvoir. Son acte constitue une insubordination caractérisée envers sa hiérarchie, qui le condamnera à mort par contumace en août 1940. Il parle en son nom propre, au nom d'une France qu'il incarne seul à ce moment.",
    nasdiS: "Diffusé le 18 juin 1940 sur la BBC, le discours est peu entendu sur le moment : la France est en déroute, les communications sont coupées, les Français sont surtout soulagés que les combats s'arrêtent. Sa portée est d'abord confidentielle avant de devenir le mythe fondateur de la Résistance. Il est régulièrement rediffusé par la BBC et est aujourd'hui classé au Registre international Mémoire du monde de l'UNESCO.",
    nasdiD: "Prononcé le 18 juin 1940, le lendemain de la demande d'armistice de Pétain (17 juin). La France est en pleine débâcle militaire : Paris est occupée depuis le 14 juin, l'armée s'effondre en six semaines face à l'offensive allemande. De Gaulle prend la parole dans un moment de désarroi total et de capitulation quasi-générale pour affirmer que la France, même vaincue militairement, n'est pas morte.",
    nasdiI: "De Gaulle affirme que la guerre n'est pas perdue : c'est une bataille perdue, pas la guerre. Il appelle à poursuivre le combat aux côtés des Alliés en s'appuyant sur l'Empire colonial, l'industrie britannique et l'entrée en guerre inévitable des États-Unis. Au-delà du contenu militaire, l'appel crée l'idée d'une France libre qui refuse la défaite et le déshonneur de l'armistice — fondement moral et politique de toute la Résistance et du mythe gaulliste de la France qui n'a jamais capitulé.",
  },
  {
    slug: "amphore-euphronios",
    title: "Cratère d'Euphronios (Sarpédon)",
    year: -515,
    nature: "Céramique grecque antique",
    author: "Euphronios (peintre) et Euxithéos (potier)",
    origin: "Athènes, Grèce ; restituée à l'Italie en 2008 (Villa Giulia, Rome)",
    description: "Chef-d'œuvre de la céramique attique à figures rouges représentant la mort du héros Sarpédon, témoignage exceptionnel de l'art grec et symbole des enjeux modernes du trafic d'antiquités.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Sarpedon_Euphronios_Louvre_G103.jpg",
    color: "#C8902A",
    nasdiN: "Cratère en calice (grand vase à mélanger le vin et l'eau, utilisé dans les banquets aristocratiques) en céramique attique à figures rouges, technique inventée à Athènes vers -530 av. J.-C. Les figures mythologiques sont réservées en argile rouge sur fond noir vernissé. La précision anatomique des corps, le rendu des muscles et des expressions, et la maîtrise de la composition en font l'une des réalisations les plus abouties de cette technique.",
    nasdiA: "Euphronios est considéré comme l'un des plus grands peintres de vases de l'Antiquité grecque — ses contemporains le reconnaissaient déjà comme tel. Ses œuvres signées sont extrêmement rares (une dizaine de pièces) et d'une qualité exceptionnelle. Pline l'Ancien le mentionne dans son Histoire naturelle. Le potier Euxithéos a fabriqué le vase, et les deux artisans ont signé leurs noms respectifs sur la céramique.",
    nasdiS: "Découvert dans une tombe étrusque de Cerveteri (Italie) vers 1971 dans des circonstances controversées (fouilles clandestines), le vase est vendu illégalement au Metropolitan Museum de New York en 1972 pour un million de dollars — prix record à l'époque. Sa restitution à l'Italie en 2008, après des années de négociation, est devenue un cas d'école dans le débat sur la restitution des antiquités pillées aux musées occidentaux.",
    nasdiD: "Réalisé vers -515 à -500, pendant l'apogée de la démocratie athénienne naissante sous Clisthène. Cette période est un âge d'or de la céramique attique, dont les productions sont exportées dans tout le monde méditerranéen — y compris en Étrurie (Italie centrale), où les élites étrusques les utilisent lors de leurs banquets funèbres. Ce vase témoigne de l'intensité des échanges commerciaux et culturels entre la Grèce et ses voisins.",
    nasdiI: "Le vase illustre la scène de la mort du héros troyen Sarpédon, fils de Zeus, transporté par les jumeaux Hypnos (Sommeil) et Thanatos (Mort) vers sa terre natale — scène tirée de l'Iliade d'Homère. Au-delà de la beauté artistique, ce cratère est un document sur la vision grecque de la mort héroïque, sur les rites funèbres aristocratiques, et sur les questions brûlantes d'aujourd'hui : à qui appartient le patrimoine archéologique de l'humanité ?",
  },
  {
    slug: "lettre-galilee",
    title: "Lettre à la Grande-Duchesse Christine",
    year: 1615,
    nature: "Lettre manuscrite",
    author: "Galileo Galilei",
    origin: "Florence, Italie ; Bibliothèque nationale centrale de Florence",
    description: "Lettre dans laquelle Galilée défend la compatibilité entre l'héliocentrisme de Copernic et les Écritures, document fondateur du débat sur la séparation entre science et religion.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/10/Galileo_Galilei_-_Letter_to_Benedetto_Castelli.jpg",
    color: "#2E8A6E",
    nasdiN: "Longue lettre manuscrite en italien (environ 50 pages dans sa version complète), adressée à Christine de Lorraine, Grande-Duchesse de Toscane et mère du Grand-Duc Cosme II, mécène de Galilée. Ce n'est pas un traité scientifique mais un document politique et apologétique : Galilée y défend sa position scientifique sur le modèle héliocentrique de Copernic en utilisant les arguments de l'Église elle-même — citations bibliques et Pères de l'Église.",
    nasdiA: "Galileo Galilei (1564-1642), mathématicien et philosophe naturel à la cour des Médicis de Florence, est alors au sommet de sa renommée internationale après ses révolutionnaires observations télescopiques (lunes de Jupiter, phases de Vénus, 1609-1610). Il s'adresse à la Grande-Duchesse car elle lui est favorable mais a exprimé des doutes théologiques, sous l'influence de théologiens conservateurs qui commencent à signaler Galilée à l'Inquisition.",
    nasdiS: "Rédigée en 1615 mais non publiée du vivant de Galilée, la lettre circule sous forme de copies manuscrites et est transmise à l'Inquisition romaine par ses ennemis dominicains. En 1616, l'héliocentrisme est condamné comme formellement hérétique. Galilée est jugé par l'Inquisition en 1633 et contraint d'abjurer sous peine de mort. La lettre devient un document emblématique de la liberté intellectuelle et du courage intellectuel face à la censure.",
    nasdiD: "Écrite en 1615, dans un contexte de tensions croissantes entre les partisans de Copernic et l'Église catholique post-tridentine engagée dans la Contre-Réforme. L'Inquisition est à son apogée et la condamnation de Giordano Bruno (brûlé vif en 1600 pour ses thèses cosmologiques) est dans toutes les mémoires. Galilée tente une approche préventive et diplomatique pour éviter la confrontation directe — en vain.",
    nasdiI: "Galilée défend l'idée que la Bible a pour but d'enseigner la foi et le salut, non la physique : 'L'Écriture enseigne comment aller au ciel, non comment le ciel va' (citation attribuée au cardinal Baronio qu'il reprend). Il pose ainsi le principe révolutionnaire de la séparation entre les domaines de la science (qui s'appuie sur l'observation et la raison) et de la religion (qui relève de la foi). Ce texte est fondateur dans l'histoire des rapports entre raison scientifique et autorité religieuse.",
  },
  {
    slug: "proclamation-emancipation",
    title: "Proclamation d'Émancipation",
    year: 1863,
    nature: "Proclamation présidentielle",
    author: "Abraham Lincoln, Président des États-Unis",
    origin: "Washington D.C., États-Unis ; National Archives, Washington",
    description: "Déclaration du président Lincoln ordonnant l'émancipation des esclaves dans les États confédérés, tournant décisif de la guerre de Sécession et acte fondateur de l'abolition de l'esclavage aux États-Unis.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Emancipation_Proclamation_%28Abraham_Lincoln%2C_1863%29.jpg",
    color: "#B03030",
    nasdiN: "Proclamation présidentielle (executive order) rédigée en anglais juridique, composée de deux parties : la proclamation préliminaire du 22 septembre 1862 et la proclamation définitive du 1er janvier 1863. Ce n'est pas un texte de loi voté par le Congrès mais un acte unilatéral du président en tant que commandant en chef des armées, fondé sur ses pouvoirs de guerre. Sa portée juridique immédiate est donc limitée aux États en sécession.",
    nasdiA: "Abraham Lincoln (1809-1865), 16e président des États-Unis, républicain anti-esclavagiste élu en 1860. Sa position a évolué au cours de la guerre : il déclare initialement que son objectif est de préserver l'Union, pas d'abolir l'esclavage. En 1862, il comprend que l'émancipation est une nécessité militaire (priver le Sud de sa main-d'œuvre) et morale pour obtenir le soutien de l'Europe et des Noirs américains libres.",
    nasdiS: "Reçue avec des réactions contrastées : applaudie par les abolitionnistes du Nord et les esclaves eux-mêmes (dont 180 000 rejoindront l'armée de l'Union), critiquée par les Démocrates du Nord qui y voient un élargissement non démocratique des objectifs de la guerre. En pratique, elle libère peu d'esclaves immédiatement (uniquement dans les États rebelles inaccessibles à l'armée de l'Union), mais son impact symbolique est immense.",
    nasdiD: "Émise le 1er janvier 1863, après la bataille d'Antietam (17 septembre 1862) — la journée la plus sanglante de la guerre avec 23 000 morts et blessés — que Lincoln utilise comme victoire suffisante pour justifier l'annonce. La guerre de Sécession (1861-1865) est alors à mi-parcours et le Nord peine à obtenir des victoires décisives. L'émancipation transforme le conflit d'une guerre pour l'Union en une guerre pour la liberté.",
    nasdiI: "La Proclamation d'Émancipation transforme radicalement les objectifs et la nature de la guerre de Sécession en en faisant une guerre pour l'abolition de l'esclavage. Elle ouvre l'armée de l'Union aux soldats noirs (175 000 combattront), décourage l'intervention britannique et française dans le camp sudiste (leurs opinions publiques étant anti-esclavagistes), et prépare le terrain pour le 13e Amendement (1865) qui abolira définitivement l'esclavage dans toute l'Amérique.",
  },
];

async function main() {
  await prisma.source.deleteMany();

  for (const source of sources) {
    await prisma.source.create({ data: source });
  }

  console.log(`✓ ${sources.length} sources historiques insérées en base de données.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
