import "dotenv/config";
import ws from "ws";
import { neonConfig } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "../src/generated/prisma";

neonConfig.webSocketConstructor = ws;

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const figures = [
  // ── ANTIQUITÉ (#C8902A) ────────────────────────────────────────────────────
  {
    slug: "socrate",
    name: "Socrate",
    birthYear: -470,
    deathYear: -399,
    role: "Philosophe",
    origin: "Athènes, Grèce",
    color: "#C8902A",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Socrate_du_Louvre.jpg/400px-Socrate_du_Louvre.jpg",
    excerpt: "Père de la philosophie occidentale, il n'a rien écrit et tout transmis par la parole.",
    bioYouth: "Né vers 470 avant J.-C. à Athènes, Socrate est le fils d'un sculpteur nommé Sophronisque et d'une sage-femme, Phénarète. Cette double ascendance artisanale marquera toute sa pensée : il se dira lui-même 'accoucheur d'idées', pratiquant une maïeutique qui aide les esprits à mettre au monde ce qu'ils portent en eux. Jeune homme, il reçoit une éducation classique athénienne, apprend la musique, la gymnastique et les rudiments de géométrie. Il côtoie les sophistes et s'en distingue aussitôt : là où ceux-ci monnaient leur savoir, il affirme n'en posséder aucun. La célèbre réponse de l'oracle de Delphes — 'Nul n'est plus sage que Socrate' — ne le surprendra pas : si les autres ignorent qu'ils ignorent, lui seul sait qu'il ne sait rien.",
    bioApogee: "Durant les décennies suivantes, Socrate arpente les rues, les gymnases et les agoras d'Athènes, engageant tout un chacun dans le dialogue. Sa méthode, l'elenchus, consiste à questionner ses interlocuteurs jusqu'à ce que leurs certitudes s'effondrent sous leur propre poids. Il interroge les politiciens sur ce qu'est la justice, les poètes sur ce qu'est la beauté, les généraux sur ce qu'est le courage. Aucun ne résiste. Marié à Xanthippe — dont la mauvaise humeur légendaire est peut-être une invention postérieure —, père de trois fils, il mène néanmoins une vie frugale et désargentée, refusant toute rétribution. Il combat vaillamment à Potidée, Délion et Amphipolis, montrant un courage physique égal à celui de sa pensée. Sa célébrité, immense dans Athènes, lui vaut autant d'admirateurs fervents — Platon, Alcibiade, Xénophon — que d'ennemis redoutables.",
    bioLegacy: "En 399 avant J.-C., accusé d'impiété et de corruption de la jeunesse, Socrate comparaît devant un tribunal de cinq cents citoyens. Il refuse de fuir, refuse de plaider coupable, et refuse même d'atténuer sa peine en proposant l'exil : sa mission divine le commande de rester. Condamné à boire la ciguë, il meurt avec une sérénité qui stupéfie ses disciples. Il n'a rien écrit, et c'est paradoxalement ce qui lui a conféré une immortalité absolue : c'est Platon qui couche sa pensée sur papier, lui donnant une dimension littéraire et philosophique que Socrate lui-même n'aurait peut-être jamais atteinte seul. Deux millénaires et demi plus tard, la méthode socratique irrigue encore le droit, l'enseignement, la psychothérapie et la philosophie. Socrate demeure le symbole irréductible de la pensée libre face au pouvoir.",
  },
  {
    slug: "alexandre-grand",
    name: "Alexandre le Grand",
    birthYear: -356,
    deathYear: -323,
    role: "Roi et conquérant",
    origin: "Pella, Macédoine",
    color: "#C8902A",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Alexander_the_Great_mosaic.jpg/400px-Alexander_the_Great_mosaic.jpg",
    excerpt: "En treize ans de campagnes ininterrompues, il bâtit l'empire le plus vaste de l'Antiquité.",
    bioYouth: "Né en 356 avant J.-C. à Pella, capitale du royaume de Macédoine, Alexandre est le fils du roi Philippe II et d'Olympias, princesse d'Épire réputée pour son tempérament passionné et ses pratiques mystiques. Dès l'enfance, il révèle une nature double : une intelligence foudroyante héritée de son père, et une fougue romantique insufflée par sa mère. À l'âge de treize ans, Philippe confie son éducation au plus grand intellectuel du monde grec : Aristote. Pendant trois ans, le futur conquérant est formé à la philosophie, à la médecine, à la rhétorique et à la poésie. Il dévore l'Iliade et se prend pour un nouveau Achille. À seize ans, il écrase déjà une rébellion en l'absence de son père. À dix-huit, il commande l'aile gauche de la cavalerie macédonienne à Chéronée, victoire décisive qui soumet la Grèce entière à la Macédoine.",
    bioApogee: "À vingt ans, à la mort de Philippe assassiné, Alexandre hérite d'un trône fragile et d'une armée aguerrie. Il liquide ses rivaux avec une rapidité terrifiante, restaure l'ordre en Grèce en rasant Thèbes en guise d'avertissement, puis franchit l'Hellespont en 334. Il débute alors la conquête de l'empire perse achéménide, le plus puissant du monde connu. En moins de dix ans, il enchaîne les victoires : Granique, Issos, Gaugamèles. Il prend Persépolis, brûle le palais de Darius, atteint l'Égypte où on le proclame pharaon et fils d'Amon, fonde Alexandrie, puis pousse jusqu'en Bactriane et dans l'actuel Pakistan. Ses soldats, exténués, refusent de franchir l'Indus. Il obéit à contrecœur. En douze années de campagnes sans défaite, il a constitué un empire de cinq millions de kilomètres carrés, stretching de la Grèce à l'Himalaya.",
    bioLegacy: "Alexandre meurt à Babylone en 323 avant J.-C., à trente-deux ans, d'une fièvre foudroyante dont la cause précise reste débattue — typhus, empoisonnement, excès d'alcool. Sa disparition est aussi soudaine que sa conquête : à son dernier souffle, quand on lui demande à qui il lègue son empire, il murmure 'au plus fort'. Ses généraux, les Diadoques, se déchirent et démembrent immédiatement ses terres. Mais son œuvre culturelle est indestructible : l'hellénisation du Moyen-Orient et de l'Asie centrale, la fondation de dizaines de villes portant son nom, la diffusion de la langue grecque comme lingua franca, et l'émergence de la période hellénistique constituent une révolution civilisationnelle durable. Deux mille ans après sa mort, Alexandre est encore la figure tutélaire de tous les conquérants.",
  },
  {
    slug: "jules-cesar",
    name: "Jules César",
    birthYear: -100,
    deathYear: -44,
    role: "Général et homme d'État",
    origin: "Rome, République romaine",
    color: "#C8902A",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Julius_Caesar_%28100-44_BC%29.jpg/400px-Julius_Caesar_%28100-44_BC%29.jpg",
    excerpt: "Général de génie et politique redoutable, il transforma la République romaine en Empire.",
    bioYouth: "Né en 100 avant J.-C. dans une famille patricienne de rang second, les Julii, César grandit dans un Rome traversée de tensions politiques violentes entre optimates et populares. Son père meurt quand il a seize ans ; sa tante Julie épouse Marius, chef des populares — ce qui lui vaut immédiatement l'hostilité de Sylla, le dictateur adverse. Refusant de divorcer sur ordre de Sylla, le jeune César s'exile momentanément. Il part étudier la rhétorique à Rhodes, où selon la légende des pirates le capturent et l'exigent en rançon : il les traite avec un mépris amusé, promet de les faire crucifier une fois libre, et tient parole. De retour à Rome, il commence une carrière politique méthodique, dépensant des sommes folles pour acheter popularité et clientèles.",
    bioApogee: "Consul en 59, puis proconsul des Gaules de 58 à 50, César mène l'une des campagnes militaires les plus brillantes de l'Histoire. En huit ans, il soumet la Gaule entière, repoussant les Germains, traversant le Rhin, débarquant même en Bretagne. Ses Commentaires de la guerre des Gaules, rédigés avec une clarté redoutable, sont aussi un chef-d'œuvre de propagande personnelle. Rappelé à Rome et invité à déposer les armes, il franchit le Rubicon en 49, déclenchant la guerre civile. Il écrase Pompée, son ancien allié devenu rival, à Pharsale en 48. En Égypte, il rencontre Cléopâtre. Il pacifie l'Orient, l'Afrique, l'Espagne. Nommé dictateur à vie en 44, il concentre entre ses mains un pouvoir sans précédent, réforme le calendrier (le calendrier julien portera son nom), engage des travaux publics colossaux.",
    bioLegacy: "Les Ides de mars 44 avant J.-C. scellent son destin : vingt-trois coups de poignard, au pied de la statue de Pompée, le terrassent. Ses assassins, Brutus et Cassius en tête, croient avoir sauvé la République. Ils ont en réalité signé sa mort définitive. La guerre civile qui suit aboutit à la victoire d'Octave, le petit-neveu de César, qui devient Auguste et premier vrai empereur de Rome. César n'a jamais été officiellement 'emperor' mais son nom est devenu synonyme de pouvoir suprême : Kaiser en allemand, Tsar en russe, César en arabe. Son calendrier julien régit l'Europe pendant seize siècles. Ses écrits militaires sont encore étudiés dans les écoles de guerre. Il est l'archétype de l'homme providentiel qui brise les institutions pour les remodeler à son image — pour le meilleur et pour le pire.",
  },
  {
    slug: "cleopatre",
    name: "Cléopâtre VII",
    birthYear: -69,
    deathYear: -30,
    role: "Reine d'Égypte",
    origin: "Alexandrie, Égypte",
    color: "#C8902A",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Kleopatra-VII.-Altes-Museum-Berlin1.jpg/400px-Kleopatra-VII.-Altes-Museum-Berlin1.jpg",
    excerpt: "Dernière reine de la dynastie ptolémaïque, polyglotte et stratège, elle pesa sur le destin de Rome.",
    bioYouth: "Née en 69 avant J.-C. à Alexandrie, Cléopâtre VII Philopator est la fille du pharaon Ptolémée XII Aulète. Elle grandit dans le palais d'Alexandrie, au cœur de la bibliothèque la plus riche du monde antique, et reçoit une éducation exceptionnelle. Contrairement à ses ancêtres ptolémaïques qui dédaignaient l'égyptien, elle apprend cette langue ainsi que le latin, l'araméen, l'éthiopien et plusieurs autres — neuf langues en tout, dit-on. Elle est la première de sa lignée à s'adresser directement à ses sujets dans leur propre idiome. À dix-huit ans, elle monte sur le trône aux côtés de son jeune frère Ptolémée XIII, qu'elle doit épouser selon la coutume. La rivalité entre eux dégénère rapidement : chassée d'Alexandrie par les partisans de son frère, elle lève une armée et attend l'occasion de renverser la situation.",
    bioApogee: "L'occasion arrive sous la forme de Jules César, débarqué en Égypte en 48 avant J.-C. à la poursuite de Pompée. Selon la légende, Cléopâtre se fait enrouler dans un tapis pour être introduite en secret dans ses appartements. Que la scène soit réelle ou non, elle séduit César, obtient son appui militaire, reprend le trône et noue avec Rome une alliance qui garantit la survie de son royaume. Elle donne à César un fils, Césarion. Après l'assassinat de César en 44, elle se tourne vers Marc Antoine, le triumvir maître de l'Orient romain, qu'elle rencontre à Tarse en 41. Leur union, à la fois politique et passionnelle, dure dix ans. Elle lui donne trois enfants. Ensemble, ils s'arrogent des territoires orientaux et se présentent comme des divinités — elle en Isis, lui en Dionysos —, ce qui scandalise Rome et donne à Octave le prétexte d'une guerre.",
    bioLegacy: "La bataille d'Actium en 31 avant J.-C. est décisive : la flotte d'Antoine et Cléopâtre est écrasée par Octave. Antoine, trompé par une fausse nouvelle de la mort de Cléopâtre, se suicide. Cléopâtre, refusant d'être exhibée dans le triomphe d'Octave à Rome, se donne la mort en 30, selon la tradition par la morsure d'un aspic. Elle a trente-neuf ans. L'Égypte devient province romaine. Avec elle s'éteint la dernière grande monarchie hellénistique et la plus longue civilisation de l'histoire humaine. Le mythe de Cléopâtre — qui n'a pas la beauté que lui prêteront les siècles, mais une intelligence et un charisme dévastateurs — n'a jamais cessé de fasciner. Elle demeure le symbole d'une femme qui joua à armes égales avec les plus grands hommes de son temps, dans un monde qui ne lui en donnait pas le droit.",
  },

  // ── MOYEN ÂGE (#7B4F9E) ───────────────────────────────────────────────────
  {
    slug: "charlemagne",
    name: "Charlemagne",
    birthYear: 742,
    deathYear: 814,
    role: "Roi des Francs et Empereur",
    origin: "Aix-la-Chapelle (actuelle Allemagne)",
    color: "#7B4F9E",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Charlemagne-by-Durer.jpg/400px-Charlemagne-by-Durer.jpg",
    excerpt: "Père de l'Europe, il réunifie l'Occident sous une même couronne après des siècles de fragmentation.",
    bioYouth: "Né vers 742 dans le royaume des Francs — on ne sait pas exactement où —, Charles est le fils aîné de Pépin le Bref, fondateur de la dynastie carolingienne, et de Bertrade de Laon. Il grandit dans un monde de violence et de foi, où les rois francs chevauchent autant qu'ils prient. À la mort de Pépin en 768, le royaume est partagé entre lui et son frère Carloman. Trois ans plus tard, Carloman meurt prématurément, et Charles hérite d'un royaume unifié. Dès lors, il ne s'arrêtera plus. Grand, robuste, parlant plusieurs langues (le latin, le roman, probablement un dialecte germanique), il est décrit comme un homme d'une énergie et d'une curiosité inépuisables, passant ses soirées à écouter des lectures à voix haute et regrettant de ne pas savoir écrire.",
    bioApogee: "Durant quarante ans de règne effectif, Charlemagne mène des campagnes militaires incessantes : contre les Saxons qu'il convertit de force au christianisme en trente ans de guerre, contre les Lombards qu'il écrase en Italie, contre les Avars en Europe centrale, contre les Maures en Espagne où il subit sa seule défaite notable (Roncevaux, 778, qui fera naître la Chanson de Roland). Le 25 décembre 800, à Rome, le pape Léon III pose sur sa tête la couronne d'empereur des Romains — geste surprenant qui reconstruit symboliquement l'Empire romain en Occident après trois siècles d'absence. Charlemagne y consent avec une feinte réticence. Cette couronnement crée le précédent que tous les empereurs d'Occident invoqueront pendant mille ans. En parallèle, il impulse la renaissance carolingienne : réforme de l'écriture (la minuscule carolingienne devient le standard européen), création d'écoles dans chaque évêché, invitation à sa cour d'Alcuin d'York et des plus grands esprits de l'époque.",
    bioLegacy: "Mort à Aix-la-Chapelle en 814, Charlemagne lègue un empire immense mais fragile. Ses petits-fils le démembreront au traité de Verdun en 843, établissant les frontières rudimentaires de la France, de l'Allemagne et de l'Italie. Mais son héritage est incalculable : il a refondé l'idée d'Europe comme espace culturel et politique commun, imposé le christianisme comme ciment civilisationnel, standardisé l'écriture et l'administration. Il est à la fois le père de la France et de l'Allemagne — deux nations qui, au XXe siècle, réconciliées après des siècles de guerres, choisiront symboliquement Aix-la-Chapelle comme lieu de signature de leur traité d'amitié. Ce n'est pas un hasard : Charlemagne est l'ancêtre commun de l'idée européenne.",
  },
  {
    slug: "jeanne-darc",
    name: "Jeanne d'Arc",
    birthYear: 1412,
    deathYear: 1431,
    role: "Héroïne et sainte nationale",
    origin: "Domrémy, France",
    color: "#7B4F9E",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Joan_of_Arc_miniature_graded.jpg/400px-Joan_of_Arc_miniature_graded.jpg",
    excerpt: "Jeune paysanne animée par des voix célestes, elle renversa le cours de la guerre de Cent Ans.",
    bioYouth: "Née en 1412 à Domrémy, village lorrain à la frontière des zones d'influence française et bourguignonne, Jehanne — c'est son vrai prénom — grandit dans une famille de paysans aisés, profondément croyante. La France est alors déchirée par la guerre de Cent Ans : les Anglais et leurs alliés bourguignons contrôlent Paris et une grande partie du nord du pays. Le dauphin Charles VII végète sans couronnement à Bourges, privé de légitimité. C'est dans ce contexte de désastre national que la jeune fille dit entendre, à partir de treize ans, les voix de saint Michel, sainte Catherine et sainte Marguerite lui commandant d'aller bouter l'Anglais hors de France et de faire sacrer le dauphin à Reims. Pendant quatre ans, elle garde ces révélations pour elle. À dix-sept ans, elle ne peut plus attendre.",
    bioApogee: "En février 1429, vêtue en homme, Jeanne traverse deux cents kilomètres de territoire ennemi pour rejoindre Chinon et convaincre Charles VII de lui confier une armée. Elle réussit l'impossible : obtient l'écoute des capitaines, galvanise les troupes épuisées par des décennies de défaites, et lève le siège d'Orléans en neuf jours au printemps 1429 — victoire que nul stratège n'espérait. Elle remporte ensuite Patay, puis accompagne Charles VII jusqu'à Reims pour son sacre en juillet 1429, accomplissant ainsi sa mission première. Sa présence sur les champs de bataille, en armure blanche, étendard au vent, transforme le moral de l'armée française. Mais à partir de l'automne 1429, les succès se font plus rares. Capturée par les Bourguignons lors d'une sortie devant Compiègne en mai 1430, elle est vendue aux Anglais.",
    bioLegacy: "Jugée par un tribunal ecclésiastique à Rouen, accusée d'hérésie et de sorcellerie, Jeanne d'Arc est brûlée vive sur la place du Vieux-Marché le 30 mai 1431. Elle a dix-neuf ans. Charles VII, qu'elle a fait roi, ne lève pas le petit doigt pour la sauver. Vingt-cinq ans plus tard, un procès en révision la réhabilitera entièrement, reconnaissant l'iniquité du jugement. Elle est canonisée en 1920. Son exécution ne change rien au sens de la guerre : la France reprend l'avantage, et les Anglais sont définitivement chassés du territoire en 1453. Jeanne d'Arc reste l'une des figures les plus complexes de l'histoire : icône nationale récupérée par tous les courants politiques, de Napoléon à Pétain, des républicains aux nationalistes, elle échappe pourtant à toute appropriation définitive. Son mystère — une jeune paysanne analphabète qui change le destin d'un royaume — n'a jamais été entièrement dissipé.",
  },

  // ── TEMPS MODERNES (#2E8A6E) ──────────────────────────────────────────────
  {
    slug: "leonard-de-vinci",
    name: "Léonard de Vinci",
    birthYear: 1452,
    deathYear: 1519,
    role: "Artiste, ingénieur et savant",
    origin: "Vinci, Toscane, Italie",
    color: "#2E8A6E",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Leonardo_self_portrait_small.jpg/400px-Leonardo_self_portrait_small.jpg",
    excerpt: "Génie polymorphe de la Renaissance, il unit en une seule vie l'art, la science et l'invention.",
    bioYouth: "Né le 15 avril 1452 à Vinci, bourg toscan entre Florence et Pise, Léonard est le fils illégitime d'un notaire florentin, ser Piero da Vinci, et d'une paysanne prénommée Caterina. Cette naissance hors mariage le prive des droits successoraux habituels mais lui laisse une liberté que les fils légitimes n'ont pas : il n'est pas contraint de suivre la profession paternelle. Son père repère très tôt son don pour le dessin et le confie vers 1466 à l'atelier du grand peintre et sculpteur florentin Andrea del Verrocchio. C'est là que Léonard passe son adolescence et son début d'âge adulte, absorbant non seulement la peinture mais l'orfèvrerie, la sculpture, la mécanique et la musique. La légende dit que lorsque Verrocchio vit l'ange que Léonard avait peint dans une de ses compositions, il posa le pinceau et ne peignit plus jamais.",
    bioApogee: "À trente ans, Léonard quitte Florence pour Milan, où il propose ses services à Ludovic Sforza non comme peintre mais comme ingénieur militaire, architecte et musicien. Il passe dix-sept ans dans cette cour et y réalise l'essentiel de son œuvre. La Cène est peinte sur un mur du réfectoire de Santa Maria delle Grazie entre 1495 et 1498. Ses carnets — des milliers de pages en écriture spéculaire (de droite à gauche) — fourmillent de projets : machines volantes, sous-marins, blindés, machines à eau, anatomie humaine, géologie, botanique, optique. Il disséque plus de trente cadavres humains pour comprendre le fonctionnement du corps et réalise les dessins anatomiques les plus précis du monde occidental. Après l'invasion française qui chasse Sforza, il erre entre Florence (où il peint la Joconde entre 1503 et 1517 environ), Venise, Rome. Il accepte finalement l'invitation de François Ier de France.",
    bioLegacy: "Léonard termine sa vie en France, au château du Clos-Lucé à Amboise, hôte choyé de François Ier qui le visite régulièrement. Il meurt le 2 mai 1519, à soixante-sept ans, selon la légende dans les bras du roi. Il laisse une œuvre peinte étonnamment mince — une vingtaine de tableaux — mais d'une perfection absolue. Ses carnets, qui ne seront systématiquement publiés qu'au XIXe et XXe siècles, révèlent un esprit qui a anticipé des siècles d'histoire des sciences : les principes de l'hélicoptère, du parachute, de la plaques tectoniques. Léonard de Vinci est l'incarnation absolue de ce que la Renaissance a produit de plus formidable : un homme pour qui les frontières entre les disciplines n'existaient pas, convaincu que tout ce qui est visible peut être compris, et que comprendre, c'est déjà un peu créer.",
  },
  {
    slug: "nicolas-copernic",
    name: "Nicolas Copernic",
    birthYear: 1473,
    deathYear: 1543,
    role: "Astronome",
    origin: "Toruń, Prusse royale (actuelle Pologne)",
    color: "#2E8A6E",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Nikolaus_Kopernikus.jpg/400px-Nikolaus_Kopernikus.jpg",
    excerpt: "Sa théorie héliocentrique a déplacé la Terre du centre de l'univers et déclenché la révolution scientifique.",
    bioYouth: "Né le 19 février 1473 à Toruń, ville marchande de Prusse royale sous suzeraineté polonaise, Nicolaus Koppernigk — latinisé en Copernicus — est le fils d'un riche négociant en cuivre. À dix ans, la mort de son père le confie à la tutelle de son oncle maternel, Lucas Watzenrode, un prélat ambitieux qui deviendra évêque d'Ermland. Cet oncle, homme cultivé et bien introduit, lui ouvre les portes des meilleures universités d'Europe. Copernic étudie à Cracovie (1491-1495), puis part en Italie — Bologne, Rome, Padoue, Ferrare — où il se forme au droit canonique, à la médecine et à l'astronomie. Il apprend le grec, lit Ptolémée dans le texte, et commence à percevoir les tensions internes d'un système géocentrique devenu ingérable à force de corrections et d'épicycles artificiels.",
    bioApogee: "De retour en Prusse vers 1503, Copernic exerce comme chanoine et médecin tout en poursuivant ses observations astronomiques depuis la tour de sa cathédrale de Frauenbourg (Frombork). Il rédige dès 1514 un court traité manuscrit, le Commentariolus, qu'il distribue à quelques amis savants : la Terre tourne autour du Soleil, et non l'inverse. Cette affirmation renverse deux mille ans de cosmologie aristotélicienne et ptolémaïque. Pendant trente ans, il peaufine sa démonstration mathématique. Il ne publie pas par prudence, par perfectionnisme peut-être, pas par peur de l'Église — dont il est un serviteur fidèle. C'est un jeune astronome allemand, Georg Joachim Rheticus, qui vient le convaincre de publier. Le De revolutionibus orbium coelestium paraît en 1543, l'année de sa mort.",
    bioLegacy: "La tradition veut que Copernic ait reçu le premier exemplaire imprimé de son livre sur son lit de mort, le 24 mai 1543, et soit décédé quelques heures plus tard. L'Église catholique ne condamne officiellement le livre qu'en 1616, après Galilée. La révolution copernicienne ne produit ses effets qu'avec Kepler, Galilée et Newton, qui bâtissent sur ses fondations les lois de la mécanique céleste. Mais le geste de Copernic est irréversible : l'humanité n'est plus au centre de l'univers. Cette décentration cosmique, philosophiquement vertigineuse, ouvre la voie à toutes les révolutions scientifiques ultérieures. Freud la citera parmi les trois grandes blessures narcissiques de l'humanité, aux côtés de Darwin et de la psychanalyse.",
  },
  {
    slug: "galilee",
    name: "Galilée",
    birthYear: 1564,
    deathYear: 1642,
    role: "Physicien et astronome",
    origin: "Pise, Toscane, Italie",
    color: "#2E8A6E",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg/400px-Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg",
    excerpt: "Père de la physique moderne, il posa l'expérience comme fondement de la connaissance scientifique.",
    bioYouth: "Né le 15 février 1564 à Pise — la même année que Shakespeare, notera-t-on —, Galileo Galilei est le fils aîné d'un musicien théoricien cultivé mais impécunieux, Vincenzo Galilei. La famille déménage à Florence quand Galilée est enfant. Il entre au monastère de Vallombrosa à quinze ans, puis en ressort sur l'insistance de son père. Inscrit en médecine à l'Université de Pise, il abandonne rapidement pour les mathématiques qui l'enthousiasment. Il obtient un poste de professeur à Pise puis à Padoue, où il enseigne dix-huit ans les plus heureux, dit-il, de sa vie. C'est là qu'il expérimente, construit des instruments, améliore la lunette astronomique et commence à retourner le ciel avec elle.",
    bioApogee: "En 1609, ayant appris l'existence d'une lunette hollandaise, Galilée en fabrique une de bien supérieure et la pointe vers le ciel. En quelques mois, il découvre les montagnes de la Lune (qui n'est donc pas une sphère parfaite), les satellites de Jupiter (qui tournent autour de Jupiter, pas de la Terre), les phases de Vénus (preuve que Vénus orbite autour du Soleil). Son Sidereus Nuncius (1610) bouleverse l'Europe savante. Il s'installe à Florence comme 'premier mathématicien et philosophe' du grand-duc de Toscane. Son Dialogo sopra i due massimi sistemi del mondo (1632) prend clairement parti pour le système copernicien en le faisant défendre par un personnage manifestement plus intelligent que celui qui défend Ptolémée. Rome ne peut ignorer la provocation.",
    bioLegacy: "Convoqué devant l'Inquisition en 1633, à soixante-neuf ans et malade, Galilée abjure ses positions héliocentristes pour éviter le bûcher. La légende lui prête la phrase 'Et pourtant elle tourne' — apocryphe, mais symboliquement vraie. Il passe ses dernières années en résidence surveillée à Arcetri, aveugle à partir de 1638, mais dicte encore ses Discours sur deux sciences nouvelles, fondement de la mécanique classique. Mort en 1642, il est, ironie de l'histoire, la même année où naît Isaac Newton, qui achèvera l'édifice qu'il a commencé. L'Église réhabilite officiellement Galilée en 1992 — soit trois siècles et demi après son procès. Son héritage est le plus fondamental de la science moderne : la conviction que la nature obéit à des lois mathématiques que l'observation et l'expérience permettent de découvrir.",
  },
  {
    slug: "napoleon-bonaparte",
    name: "Napoléon Bonaparte",
    birthYear: 1769,
    deathYear: 1821,
    role: "Général et Empereur",
    origin: "Ajaccio, Corse",
    color: "#2E8A6E",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Napoleon_Bonaparte_%281771-1821%29.jpg/400px-Napoleon_Bonaparte_%281771-1821%29.jpg",
    excerpt: "Enfant de la Révolution devenu maître de l'Europe, il remodela les institutions d'un continent entier.",
    bioYouth: "Né le 15 août 1769 à Ajaccio, en Corse — île française depuis un an seulement —, Napoleone di Buonaparte est le deuxième fils d'une famille de la petite noblesse corse. À neuf ans, il est envoyé dans une école militaire à Brienne-le-Château, en France, où il subit les moqueries de ses camarades pour son accent et son patriotisme corse affiché. Solitaire, studieux, il compense par des résultats brillants en mathématiques et en histoire militaire. À seize ans, il intègre l'École militaire de Paris et en sort lieutenant d'artillerie. La Révolution française éclate quand il a vingt ans. Elle le propulse dans un monde où les barrières sociales s'effondrent, où le mérite peut tout. Lieutenant à vingt, général à vingt-quatre après la reprise de Toulon aux Anglais, il comprend avant tout le monde que la Révolution a besoin d'un soldat.",
    bioApogee: "La campagne d'Italie (1796-1797), menée à vingt-six ans avec un génie tactique fulgurant, révèle Napoléon au monde. Il enchaîne victoire sur victoire contre des généraux autrichiens plus expérimentés. La campagne d'Égypte (1798-1799), moins militairement concluante, lui donne une dimension orientale et savante : il emmène des savants qui décrivent l'Égypte ancienne et moderne, découvrent la pierre de Rosette. Revenu en France au bon moment, il s'empare du pouvoir par le coup d'État du 18 Brumaire (1799), devient consul, puis Premier consul, puis Consul à vie (1802), puis Empereur (1804). Sous son règne, il réforme la France en profondeur : Code civil (qui porte encore son nom), Légion d'honneur, lycées, Banque de France, concordat avec le pape. Sur les champs de bataille, Austerlitz (1805), Iéna (1806) et Wagram (1809) sont des chefs-d'œuvre tactiques sans équivalents.",
    bioLegacy: "La retraite de Russie en 1812 commence la désagrégation. Après l'abdication de 1814, l'exil à l'île d'Elbe, les Cent-Jours et la défaite de Waterloo en 1815, Napoléon est exilé à Sainte-Hélène, île perdue dans l'Atlantique sud. Il y passe six ans à dicter ses Mémoires, construisant la légende napoléonienne avec le même soin qu'il construisait ses batailles. Il meurt en 1821, à cinquante et un ans, probablement d'un cancer de l'estomac. Son corps est ramené à Paris en 1840, enterré aux Invalides avec la pompe d'un empire. Son héritage est double et indissociable : les institutions qu'il a bâties structurent encore la France du XXIe siècle ; les guerres qu'il a menées ont semé la mort à travers toute l'Europe. Napoléon Bonaparte reste l'homme qui a le plus profondément marqué la France depuis Charlemagne — en bien et en mal.",
  },

  // ── ÉPOQUE CONTEMPORAINE (#B03030) ────────────────────────────────────────
  {
    slug: "abraham-lincoln",
    name: "Abraham Lincoln",
    birthYear: 1809,
    deathYear: 1865,
    role: "Président des États-Unis",
    origin: "Hardin County, Kentucky, États-Unis",
    color: "#B03030",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg/400px-Abraham_Lincoln_O-77_matte_collodion_print.jpg",
    excerpt: "Il préserva l'Union américaine et abolit l'esclavage au prix de sa vie et d'une guerre civile dévastatrice.",
    bioYouth: "Né le 12 février 1809 dans une cabane en rondins du Kentucky, Abraham Lincoln grandit dans une pauvreté rurale qui façonne durablement son caractère. Son père, Thomas Lincoln, est fermier itinérant. Sa mère, Nancy Hanks, meurt d'une fièvre laiteuse quand Abraham a neuf ans. Sa belle-mère, Sarah Bush Johnston, encourage son goût pour la lecture — il se forme en autodidacte, dévorant la Bible, Ésope, Shakespeare et Blackstone sur les lois. Il ne va à l'école qu'en tout et pour tout environ un an. Adolescent, il travaille comme batelier sur l'Ohio et le Mississippi, vend des marchandises, fend du bois. À New Salem, Illinois, il ouvre une épicerie, étudie le droit seul la nuit, et entre en politique locale. Il est élu à l'assemblée de l'Illinois à vingt-cinq ans, et devient avocat reconnu à Springfield. Sa réputation d'honnêteté absolue lui vaut le surnom 'Honest Abe'.",
    bioApogee: "Élu au Congrès fédéral en 1846, Lincoln s'oppose à la guerre contre le Mexique et en paie le prix politique, restant un seul mandat. Il revient à sa pratique d'avocat jusqu'à ce que la question de l'esclavage et l'extension dans les nouveaux États le rappelle au combat. Ses débats contre Stephen Douglas (1858) pour le Sénat de l'Illinois le révèlent au niveau national comme un orateur d'une clarté morale rare. Élu président républicain en novembre 1860, il provoque la sécession des États du Sud avant même sa prise de fonctions. La guerre de Sécession débute en avril 1861. Il gère quatre années d'une guerre d'une brutalité inédite — six cent mille morts —, résistant aux pressions pour négocier, soutenant des généraux jusqu'à trouver le bon (Grant), émettant la Proclamation d'émancipation le 1er janvier 1863, qui libère les esclaves des États confédérés et donne à la guerre une dimension morale irréversible. Réélu en 1864, il prononce son second discours inaugural, un chef-d'œuvre de réconciliation.",
    bioLegacy: "Le 14 avril 1865, cinq jours après la reddition du général Lee qui met fin à la guerre, Abraham Lincoln est abattu d'une balle dans la nuque au Ford's Theatre de Washington par John Wilkes Booth, acteur sudiste fanatique. Il meurt le lendemain matin. Il ne verra pas la ratification du Treizième Amendement abolissant l'esclavage — qu'il a porté —, ni la difficile reconstruction du Sud. Sa mort le sanctifie immédiatement : martyrisé au moment de la victoire, il devient la figure tutélaire de l'unité américaine. Les historiens américains le classent régulièrement comme le premier ou le deuxième président le plus important de l'histoire des États-Unis. Son portrait orne le billet de cinq dollars, son mémorial domine le National Mall. Il reste le symbole d'une démocratie capable de se remettre en question jusqu'au sacrifice de ses enfants.",
  },
  {
    slug: "charles-darwin",
    name: "Charles Darwin",
    birthYear: 1809,
    deathYear: 1882,
    role: "Naturaliste et biologiste",
    origin: "Shrewsbury, Angleterre",
    color: "#B03030",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Charles_Darwin_seated_crop.jpg/400px-Charles_Darwin_seated_crop.jpg",
    excerpt: "Sa théorie de l'évolution par sélection naturelle révolutionna la biologie et la place de l'homme dans le vivant.",
    bioYouth: "Né le 12 février 1809 — le même jour qu'Abraham Lincoln — à Shrewsbury, dans le Shropshire, Charles Darwin est le cinquième de six enfants d'un médecin prospère, Robert Darwin. Sa mère meurt quand il a huit ans. Enfant, il est passionné de collection : coquillages, minéraux, insectes, tout l'attire dans la nature. Envoyé étudier la médecine à Édimbourg, il déteste les salles d'opération et abandonne. On le dirige vers Cambridge pour devenir pasteur — voie honnête pour un jeune gentleman de bonne famille. À Cambridge, il découvre la botanique avec John Stevens Henslow, qui devient son mentor. Ce même Henslow le recommande en 1831 pour accompagner le capitaine Robert FitzRoy à bord du HMS Beagle, une corvette de la Royal Navy qui doit cartographier les côtes d'Amérique du Sud. Darwin a vingt-deux ans.",
    bioApogee: "Le voyage du Beagle dure cinq ans (1831-1836) et emmène Darwin autour du monde : Brésil, Patagonie, îles Malouines, côte pacifique de l'Amérique du Sud, archipel des Galápagos, Tahiti, Australie, îles Cocos, cap de Bonne-Espérance. Aux Galápagos, en 1835, il observe les fameux pinsons dont les becs varient selon les îles en fonction des ressources alimentaires disponibles — observation qui germera longtemps avant de porter ses fruits. De retour en Angleterre, Darwin passe vingt ans à rassembler preuves et arguments. Il sait ce qu'il va publier et mesure le séisme que ça provoquera. Un autre naturaliste, Alfred Russel Wallace, arrive aux mêmes conclusions simultanément en 1858. Les deux hommes présentent conjointement leurs travaux à la Société linnéenne. En 1859, Darwin publie De l'origine des espèces, l'un des livres les plus importants jamais écrits : toutes les espèces descendent d'ancêtres communs par le mécanisme de la sélection naturelle — les mieux adaptés survivent et se reproduisent davantage.",
    bioLegacy: "L'onde de choc est immédiate et durable. Le livre se vend en quelques heures. L'Église et une partie du monde scientifique s'insurgent ; d'autres savants embrassent la théorie. Darwin évite soigneusement, dans l'Origine, de parler de l'homme — il attendra 1871 pour le faire dans La Filiation de l'homme. Retiré à Down House dans le Kent en raison d'une mystérieuse maladie chronique qui l'affecte une vie entière, il continue de travailler méthodiquement, publiant sur les orchidées, les vers de terre, l'expression des émotions. Il meurt en 1882, honoré par tous, et est enterré à Westminster Abbey à côté de Newton. La théorie de l'évolution est aujourd'hui le fondement unificateur de toute la biologie. Elle a aussi profondément transformé la philosophie, la psychologie et la vision de la place de l'humanité dans le vivant : nous ne sommes pas séparés de la nature, mais issus d'elle.",
  },
  {
    slug: "marie-curie",
    name: "Marie Curie",
    birthYear: 1867,
    deathYear: 1934,
    role: "Physicienne et chimiste",
    origin: "Varsovie, Pologne (sous domination russe)",
    color: "#B03030",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Marie_Curie_c._1920s.jpg/400px-Marie_Curie_c._1920s.jpg",
    excerpt: "Première femme Prix Nobel — deux fois — elle découvrit le polonium et le radium.",
    bioYouth: "Née le 7 novembre 1867 à Varsovie — alors sous occupation russe, où parler polonais à l'école est interdit —, Maria Sklodowska est la benjamine de cinq enfants d'un couple d'enseignants. Son père, professeur de physique, l'initie très tôt aux sciences. Sa mère meurt de tuberculose quand Maria a onze ans. Brillante élève, elle obtient son baccalauréat avec mention mais ne peut accéder aux universités polonaises, fermées aux femmes. Elle passe un accord avec sa sœur aînée Bronia : elle financera les études de médecine de Bronia à Paris, qui en retour financera les siennes. Pendant six ans, elle travaille comme gouvernante dans des familles de province. En 1891, à vingt-quatre ans, elle rejoint enfin Paris et s'inscrit à la Sorbonne. Elle y vit dans un froid et une pauvreté extrêmes, mangeant parfois du chocolat comme seul repas. Elle est première de sa licence de physique en 1893, et obtient aussi une licence de mathématiques en 1894.",
    bioApogee: "En 1894, elle rencontre Pierre Curie, physicien de huit ans son aîné, dans un laboratoire commun. Ils se marient en 1895 et constituent l'un des plus grands duos scientifiques de l'histoire. Choisissant d'étudier les rayons uraniques découverts par Becquerel, Marie développe le concept de radioactivité — mot qu'elle crée — et démontre que l'émission de rayons est une propriété atomique, pas moléculaire. Elle découvre le polonium (nommé en hommage à sa patrie occupée) en juillet 1898, puis le radium en décembre 1898. En 1903, elle soutient la première thèse de doctorat scientifique d'une femme en France. La même année, elle reçoit avec Pierre et Becquerel le prix Nobel de physique. En 1906, Pierre est renversé et tué par un camion dans une rue de Paris. Marie reprend seule son poste de professeure à la Sorbonne — première femme à y enseigner. En 1911, elle reçoit un second prix Nobel, cette fois de chimie, pour l'isolement du radium pur.",
    bioLegacy: "Marie Curie meurt le 4 juillet 1934 d'une anémie aplasique causée par l'exposition prolongée aux radiations qu'elle a manipulées durant toute sa carrière, sans protection — on ne savait pas encore. Elle a laissé sa santé dans ses laboratoires. Son corps a été transféré au Panthéon en 1995 avec celui de Pierre — elle est la première femme à y entrer à titre de ses propres mérites, et non de ceux de son mari. La radioactivité qu'elle a découverte et nommée fonde la médecine nucléaire, la radiothérapie contre le cancer, et l'énergie nucléaire. Elle reste le symbole mondial de l'excellence scientifique féminine face aux préjugés d'une époque — et une figure de courage intellectuel que les décennies n'ont pas effacée.",
  },
  {
    slug: "albert-einstein",
    name: "Albert Einstein",
    birthYear: 1879,
    deathYear: 1955,
    role: "Physicien théoricien",
    origin: "Ulm, Allemagne",
    color: "#B03030",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/400px-Albert_Einstein_Head.jpg",
    excerpt: "Sa théorie de la relativité transforma notre compréhension de l'espace, du temps et de la gravité.",
    bioYouth: "Né le 14 mars 1879 à Ulm, dans le Wurtemberg, Albert Einstein est le fils d'un commerçant en matériel électrique juif, Hermann Einstein, et d'une mère musicienne, Pauline Koch. Sa famille déménage à Munich, puis à Milan quand son père échoue en affaires. Adolescent, Einstein manifeste déjà une pensée indépendante et rétive à l'autorité : il abandonne le lycée allemand autoritaire qu'il supporte mal et rejoint ses parents en Italie. Recalé une première fois au concours d'entrée de l'École polytechnique de Zurich, il y entre l'année suivante. Il en sort diplômé en 1900 mais, sans relation, ne trouve pas de poste universitaire. En 1902, il entre à l'Office fédéral de la propriété intellectuelle de Berne comme expert technique de troisième classe. C'est là, dans ce poste subalterne, qu'il pense.",
    bioApogee: "L'année 1905 est son annus mirabilis : en quelques mois, il publie cinq articles qui révolutionnent la physique. L'un explique l'effet photoélectrique (la lumière est faite de quanta, les photons — Nobel 1921). Un autre confirme l'existence des atomes. Le troisième et le quatrième posent les fondements de la relativité restreinte : dans un univers où la vitesse de la lumière est constante, espace et temps sont relatifs. Et E=mc², la plus célèbre équation de la science, en découle. Il faut dix ans de plus pour achever la relativité générale (1915) : la gravité n'est pas une force mais une courbure de l'espace-temps par la masse. L'éclipse de 1919, qui confirme que la lumière est déviée par la gravité du Soleil exactement comme Einstein l'avait prédit, le rend instantanément célèbre dans le monde entier. Il est le premier physicien à être une célébrité mondiale au sens moderne du terme.",
    bioLegacy: "En 1933, fuyant le nazisme — sa judaïté et son pacifisme en font une cible —, Einstein s'installe définitivement à Princeton, États-Unis. En 1939, alarmé par la perspective que l'Allemagne nazie construise une bombe atomique, il signe la lettre à Roosevelt qui débouche sur le projet Manhattan. Il le regrettera toute sa vie : la bombe d'Hiroshima le hante. Ses dernières années sont consacrées à une vaine quête d'une théorie du champ unifié, et à un engagement croissant pour la paix internationale. Il meurt à Princeton le 18 avril 1955. Son cerveau est prélevé par le médecin légiste pour étude — controverse éthique qui l'aurait amusé ou indigné, on ne sait. La relativité générale est confirmée avec une précision croissante à chaque décennie : les ondes gravitationnelles détectées en 2015 en sont la dernière et spectaculaire preuve. E=mc² reste la seule équation que le grand public reconnaît. Einstein est devenu le symbole universel du génie.",
  },
  {
    slug: "nelson-mandela",
    name: "Nelson Mandela",
    birthYear: 1918,
    deathYear: 2013,
    role: "Militant et président de l'Afrique du Sud",
    origin: "Mvezo, Afrique du Sud",
    color: "#B03030",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Nelson_Mandela_-_2008_%28edit%29.jpg/400px-Nelson_Mandela_-_2008_%28edit%29.jpg",
    excerpt: "Vingt-sept ans de prison n'ont pas brisé sa volonté : il est sorti libre pour libérer tout un pays.",
    bioYouth: "Né le 18 juillet 1918 à Mvezo, petit village du Transkei (actuelle province du Cap-Oriental), Rolihlahla Mandela est le fils du chef local Gadla Henry Mphakanyiswa, de l'ethnie Xhosa. Son prénom anglais Nelson lui est donné par son institutrice, selon la coutume. Fils d'un notable mais orphelin de père à neuf ans, il est confié à la tutelle du régent de la tribu Thembu, Jongintaba Dalindyebo, qui lui offre une excellente éducation. Il fréquente un pensionnat méthodiste, puis Fort Hare, l'unique université noire d'Afrique du Sud, d'où il est renvoyé pour avoir participé à une grève étudiante. Réfugié à Johannesburg pour échapper à un mariage arrangé, il travaille comme gardien de mine puis entre dans un cabinet d'avocats. Il achève son droit par correspondance, devient avocat en 1952 et ouvre, avec Oliver Tambo, le premier cabinet d'avocats noirs du pays.",
    bioApogee: "Engagé dans la lutte contre l'apartheid au sein de l'ANC (Congrès national africain) depuis les années 1940, Mandela crée en 1961 la branche armée Umkhonto we Sizwe ('Lance de la nation') après que le massacre de Sharpeville (1960) lui a montré les limites de la résistance non violente. Arrêté en 1962, condamné en 1964 au procès de Rivonia pour sabotage et complot, il prononce un discours de dock resté dans les annales — 'J'ai chéri l'idéal d'une société démocratique et libre (…) c'est un idéal pour lequel je suis prêt à mourir' — et refuse la grâce conditionnelle que lui propose le gouvernement en échange d'un renoncement à la violence armée. Il passe vingt-sept ans en prison, dix-huit à Robben Island. Il y étudie, lit, enseigne clandestinement ses camarades, maintient une dignité qui force l'admiration jusqu'à ses geôliers. Sa captivité le transforme en symbole universel.",
    bioLegacy: "Libéré le 11 février 1990 par le président F.W. de Klerk, dans un contexte de pression internationale croissante, Mandela sort du prison à soixante et onze ans et choisit la réconciliation plutôt que la revanche. Il négocie avec De Klerk le démantèlement de l'apartheid et des premières élections multiraciales. En avril 1994, il vote pour la première fois de sa vie — à soixante-quinze ans — et remporte l'élection présidentielle. Son mandat (1994-1999) est marqué par la Commission vérité et réconciliation, qui préfère le pardon à la vengeance. Il cède le pouvoir volontairement en 1999 — rareté en Afrique. Il meurt le 5 décembre 2013, à quatre-vingt-quinze ans, pleuré par le monde entier. Nelson Mandela est le symbole le plus puissant du XXe siècle que la dignité humaine peut traverser l'horreur sans se laisser corrompre — et qu'un seul homme peut changer un pays.",
  },
];

async function main() {
  for (const figure of figures) {
    await prisma.figure.upsert({
      where: { slug: figure.slug },
      update: figure,
      create: figure,
    });
  }
  console.log(`✓ ${figures.length} figures insérées/mises à jour.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
