import "dotenv/config";
import ws from "ws";
import { neonConfig } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";

neonConfig.webSocketConstructor = ws;

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const data = [
  {
    slug: "antiquite",
    label: "Antiquité",
    events: [
      {
        slug: "construction-pyramides",
        year: -2560,
        title: "Construction des pyramides",
        description: "Des dizaines de milliers d'ouvriers bâtissent les pyramides de Gizeh, les monuments les plus impressionnants jamais créés par l'être humain.",
        content: "Il y a 4 500 ans, le pharaon Khéops avait un rêve fou : construire le bâtiment le plus grand du monde pour préparer son voyage vers l'au-delà. Pour cela, il réunit des dizaines de milliers d'ouvriers venus de tout l'Égypte. Ces bâtisseurs n'étaient pas des esclaves - ils étaient nourris, soignés et logés par l'État. C'était comme un grand chantier national où tout le monde travaillait ensemble pour leur pharaon.\n\nEn 20 ans de travail, ils ont empilé plus de 2 millions de blocs de pierre, chacun aussi lourd qu'une petite voiture. La pyramide terminée était aussi haute que 40 maisons superposées ! Pour déplacer ces blocs sans grue ni machine, ils utilisaient des rampes en bois, des cordes solides et beaucoup d'ingéniosité. C'est encore aujourd'hui un mystère fascinant pour les archéologues.\n\nAujourd'hui, 4 500 ans après, les pyramides sont toujours debout. Elles nous montrent que quand des humains travaillent ensemble avec détermination, ils peuvent accomplir des choses qui semblent impossibles. Les pyramides de Gizeh sont l'une des sept merveilles du monde et des millions de visiteurs viennent les admirer chaque année. Tu peux les voir avec Google Earth depuis chez toi !",
      },
      {
        slug: "fondation-rome",
        year: -753,
        title: "Fondation de Rome",
        description: "Selon la légende, le héros Romulus fonde la ville de Rome - un village de cabanes qui deviendra la capitale du monde antique.",
        content: "Il y a environ 2 800 ans, sur les bords du fleuve Tibre en Italie, la légende raconte que deux jumeaux abandonnés, Romulus et Rémus, ont été élevés par une louve. Devenus adultes, ils décident de fonder une ville. Mais ils se disputent : sur quelle colline construire ? Romulus trace un sillon dans la terre et déclare 'Voici Rome !' - et c'est le début d'une aventure extraordinaire.\n\nAu départ, Rome est un tout petit village de cabanes en bois. Mais ses habitants sont ambitieux et organisés. Ils apprennent à se battre, à faire des lois et à accueillir les étrangers. Peu à peu, Rome grandit : d'abord une petite ville, puis une grande cité, puis une République gouvernée par des élus, et enfin un empire immense qui dirige toute l'Europe.\n\nRome nous a laissé des cadeaux que tu utilises chaque jour sans le savoir. Notre alphabet vient du latin, la langue des Romains. Les mots 'janvier' (Janus), 'mars' (Mars), 'juin' (Junius) sont des noms de dieux romains ! Les routes droites, les ponts solides, les lois écrites - tout cela vient de Rome. La ville qui a commencé comme un village de bergers a changé le monde pour toujours.",
      },
      {
        slug: "naissance-democratie",
        year: -507,
        title: "Naissance de la démocratie",
        description: "À Athènes, les citoyens obtiennent pour la première fois le droit de voter et de décider ensemble des lois de leur cité.",
        content: "Imagine que pour décider des règles de ta classe, tous les élèves puissent voter à main levée. C'est exactement ce qu'invente la cité d'Athènes il y a 2 500 ans ! Un homme politique courageux appelé Clisthène organise des grandes assemblées où tous les citoyens athéniens peuvent parler, débattre et voter les lois. Ils appellent ça la 'démocratie', ce qui veut dire 'le pouvoir du peuple' en grec.\n\nChaque semaine, des milliers d'Athéniens se réunissent sur la grande place de la ville, appelée l'Agora. N'importe quel citoyen peut monter sur l'estrade et proposer une loi. Ensuite, tout le monde vote en levant la main. Les décisions importantes - partir en guerre, signer la paix, construire un nouveau temple - sont prises ensemble. C'est une idée révolutionnaire dans un monde habitué aux rois et aux pharaons qui décident tout seuls.\n\nAujourd'hui, presque tous les pays du monde s'inspirent de cette idée née à Athènes. Quand tu vois tes parents aller voter pour élire le président de la République, ils participent à une tradition vieille de 2 500 ans. La démocratie athénienne n'était pas parfaite - les femmes, les esclaves et les étrangers n'avaient pas le droit de voter - mais elle a planté la graine d'une idée magnifique : les gens doivent pouvoir décider eux-mêmes de leur avenir.",
      },
      {
        slug: "bataille-marathon",
        year: -490,
        title: "La bataille de Marathon",
        description: "Une petite armée grecque repousse l'immense armée perse et invente par la même occasion le marathon !",
        content: "En 490 avant J.-C., une armée perse gigantesque débarque sur la plage de Marathon, près d'Athènes. Les Perses sont si nombreux que leurs bateaux couvrent toute la mer ! Ils veulent punir Athènes qui a osé se révolter contre leur empire. Les Athéniens, bien moins nombreux, doivent choisir : fuir et abandonner leur ville, ou se battre contre toute logique.\n\nLes généraux athéniens font un choix audacieux : attaquer en courant à toute vitesse. Leurs soldats, équipés de longues lances appelées sarisses, chargent si vite que les Perses n'ont pas le temps de riposter avec leurs arcs. Contre toute attente, les Grecs remportent une victoire écrasante ! La légende dit qu'un soldat du nom de Philippidès a couru 40 kilomètres d'une traite jusqu'à Athènes pour crier 'Victoire !' avant de tomber mort d'épuisement.\n\nCette course héroïque est à l'origine de l'épreuve du marathon que tu vois aux Jeux Olympiques ! Les athlètes courent exactement 42 kilomètres en souvenir de ce messager courageux. Mais au-delà du sport, la victoire de Marathon a sauvé quelque chose de précieux : la toute jeune démocratie athénienne. Si les Perses avaient gagné, la liberté de voter et de s'exprimer aurait peut-être disparu avant même de se répandre dans le monde.",
      },
      {
        slug: "mort-socrate",
        year: -399,
        title: "La mort de Socrate",
        description: "Le plus grand philosophe d'Athènes préfère mourir que de trahir ses idées - une leçon de courage qui inspire encore aujourd'hui.",
        content: "Socrate est un drôle de bonhomme que tout le monde reconnaît dans les rues d'Athènes. Il passe ses journées à poser des questions gênantes à tout le monde : 'Qu'est-ce que le courage ?' 'Comment savoir ce qui est vraiment juste ?' Il ne donne jamais de réponses - il veut que chacun réfléchisse par lui-même. Les jeunes l'adorent, mais les puissants l'aiment beaucoup moins.\n\nEn 399 avant J.-C., Socrate est arrêté et jugé devant 500 citoyens d'Athènes. On l'accuse de 'corrompre la jeunesse' et de ne pas respecter les dieux. Ses amis lui proposent de s'échapper, mais il refuse : fuir serait reconnaître qu'il a tort. Condamné à boire la ciguë, un poison, il continue à philosopher avec ses amis jusqu'à la fin, calme et serein, comme si mourir pour ses idées était la chose la plus naturelle du monde.\n\nSocrate n'a jamais écrit une seule ligne. Mais son élève Platon a tout noté, et grâce à lui, les idées de Socrate nous sont parvenues. Sa grande invention ? Apprendre à poser des questions plutôt que d'accepter les réponses toutes faites. Les professeurs de philosophie du monde entier utilisent encore sa méthode. Et son courage face à la mort a inspiré des milliers de personnes à défendre leurs convictions, même quand c'est difficile.",
      },
      {
        slug: "conquetes-alexandre",
        year: -334,
        title: "Les conquêtes d'Alexandre le Grand",
        description: "À 22 ans, Alexandre part à la conquête du monde et bâtit en 10 ans le plus grand empire jamais vu.",
        content: "Alexandre a grandi avec une seule ambition : devenir le plus grand conquérant de l'histoire. Son professeur n'est autre qu'Aristote, le philosophe le plus brillant de l'époque - imagine avoir le meilleur prof du monde ! À 22 ans, il hérite du royaume de Macédoine et décide aussitôt de partir à l'attaque de l'Empire perse, 50 fois plus grand que son pays. Tout le monde pense qu'il est fou.\n\nCe qui se passe ensuite est époustouflant. En 10 ans, Alexandre et son armée traversent déserts brûlants, montagnes enneigées et fleuves dangereux. Il bat des armées bien plus grandes grâce à sa stratégie brillante. Égypte, Perse, Afghanistan, Inde... Il conquiert tout ! Il fonde plus de 70 villes qui portent son nom, dont Alexandrie en Égypte, qui deviendra la ville la plus savante du monde.\n\nAlexandre meurt à seulement 32 ans, épuisé et malade, sans avoir pu rentrer chez lui. Mais il a changé le monde pour toujours. Partout où il est passé, il a mélangé la culture grecque avec les cultures locales : la philosophie, les mathématiques, l'art grec se répandent ainsi jusqu'en Inde. Ce grand mélange de cultures a enrichi la science et l'art pendant des siècles. Alexandre reste aujourd'hui l'un des plus grands stratèges militaires de tous les temps.",
      },
      {
        slug: "hannibal-alpes",
        year: -218,
        title: "Hannibal traverse les Alpes avec des éléphants",
        description: "Le général carthaginois réalise l'impossible : traverser les Alpes en hiver avec une armée et des éléphants de guerre pour surprendre Rome.",
        content: "Hannibal Barca est le général le plus redoutable de son époque. Il dirige Carthage, une grande ville d'Afrique du Nord, et déteste Rome qui a écrasé son pays dans une guerre terrible. Pour se venger, il conçoit un plan totalement fou : au lieu d'attaquer Rome par la mer, il va traverser l'Espagne, la France et les Alpes à pied - en hiver - avec 100 000 soldats et 37 éléphants de guerre gigantesques !\n\nLa traversée des Alpes dure 15 jours dans des conditions cauchemardesque. La neige, le froid glacial, les rochers glissants... Des milliers de soldats et plusieurs éléphants meurent pendant le voyage. Mais Hannibal ne recule jamais. Quand il arrive en Italie, les Romains sont complètement stupéfaits : personne n'imaginait qu'une armée puisse venir par là. Il bat les armées romaines l'une après l'autre et se promène en Italie pendant 15 ans !\n\nHannibal n'a finalement pas réussi à détruire Rome, mais ses stratégies militaires sont encore étudiées dans les écoles de guerre du monde entier. Des généraux comme Napoléon ont essayé de copier ses tactiques ! Et sa traversée des Alpes reste l'un des exploits militaires les plus fous de toute l'histoire. Elle nous apprend qu'avec de l'imagination et une volonté de fer, on peut faire des choses que personne d'autre n'oserait même tenter.",
      },
      {
        slug: "assassination-cesar",
        year: -44,
        title: "L'assassinat de César",
        description: "Le dirigeant le plus puissant de Rome est poignardé par ses propres amis - et paradoxalement, sa mort détruit ce qu'ils voulaient sauver.",
        content: "Jules César est l'homme le plus célèbre de Rome. Général brillant, il a conquis la Gaule (l'ancienne France) en 8 ans et ramené des richesses immenses. Le peuple l'adore ! Mais des sénateurs riches et jaloux ont peur de lui. Ils craignent qu'il veuille devenir roi et tout contrôler. Alors 23 d'entre eux décident de le tuer pour 'sauver la République'.\n\nLe 15 mars 44 avant J.-C., César arrive à une réunion du Sénat. Les comploteurs sortent leurs couteaux cachés sous leurs grandes toges. Parmi eux, il y a Brutus, l'un de ses meilleurs amis. En voyant Brutus l'attaquer, César lui dit les mots les plus tristes de toute l'Antiquité : 'Toi aussi, Brutus ?' Il reçoit 23 coups de couteau et s'effondre mort. Les assassins sont convaincus d'avoir sauvé Rome.\n\nIls ont fait exactement le contraire ! L'assassinat déclenche 17 ans de guerres civiles terribles qui ravagent tout l'Empire. À la fin, c'est Octave, le neveu de César, qui gagne tout. Il prend le nom d'Auguste et devient le premier vrai empereur de Rome - la République que les assassins voulaient protéger disparaît pour toujours. Cette histoire nous apprend une leçon importante : la violence pour résoudre un problème crée souvent des problèmes bien pires.",
      },
      {
        slug: "naissance-christianisme",
        year: 33,
        title: "Naissance du christianisme",
        description: "Un jeune charpentier de Galilée prêche l'amour du prochain et fonde sans le savoir la religion la plus répandue du monde.",
        content: "Il y a 2 000 ans, dans une petite province de l'Empire romain, un jeune homme du nom de Jésus commence à voyager de village en village avec 12 amis appelés 'disciples'. Son message est simple et révolutionnaire pour l'époque : il faut aimer son prochain, même ses ennemis, et partager avec les pauvres. Des foules immenses viennent l'écouter, surtout les gens modestes qui n'ont jamais été aimés par les puissants.\n\nLes autorités romaines et les chefs religieux voient Jésus comme un agitateur dangereux. Il est arrêté, jugé en une nuit et condamné à mourir sur une croix - la punition la plus terrible de l'époque. Ses disciples, désespérés, pensent que tout est fini. Mais les Évangiles racontent que trois jours après sa mort, Jésus ressuscite et apparaît à ses amis. C'est ce miracle de la Résurrection qui est au cœur de la foi chrétienne.\n\nAujourd'hui, le christianisme est la religion la plus répandue du monde avec plus de 2 milliards de croyants. Il a profondément changé l'art, la musique, l'architecture et les valeurs de l'Occident. Noël et Pâques rythment encore notre année. Les magnifiques cathédrales de Paris, Chartres ou Notre-Dame existent grâce à cette religion née d'un jeune homme dans un coin reculé de l'Empire romain. Son message d'amour et de solidarité inspire encore des millions de personnes chaque jour.",
      },
      {
        slug: "apogee-empire-romain",
        year: 117,
        title: "L'apogée de l'Empire romain",
        description: "Sous l'empereur Trajan, l'Empire romain atteint sa plus grande taille : 70 millions de personnes sur trois continents, reliées par 80 000 km de routes.",
        content: "En l'an 117, l'Empire romain est au sommet de sa puissance. Il s'étend de l'Écosse tout au nord jusqu'au désert du Sahara au sud, et de l'Espagne à l'ouest jusqu'à l'Irak actuel à l'est. Imagine un seul pays qui couvrirait toute l'Europe, une partie de l'Afrique et du Moyen-Orient - c'est l'Empire romain ! 70 millions de personnes vivent sous ses lois et parlent son langage.\n\nVivre dans l'Empire romain, c'est vivre dans un monde super moderne pour l'époque. Les villes romaines ont de l'eau courante grâce à des aqueducs (comme des tuyaux géants en pierre), des bains publics, des bibliothèques, des marchés et même des restaurants. Un réseau de 80 000 kilomètres de routes pavées relie tout l'empire - comme nos autoroutes aujourd'hui. 'Tous les chemins mènent à Rome', dit-on encore !\n\nL'héritage romain est partout autour de toi, même si tu ne le vois pas. Le français, l'espagnol, l'italien et le portugais descendent tous du latin. Les mots 'janvier', 'mars', 'août' viennent de noms romains. Notre façon d'organiser les villes, notre droit, notre façon d'écrire les dates - tout cela vient de Rome. L'Empire romain a agi comme un grand mélangeur culturel qui a créé le monde occidental tel que nous le connaissons.",
      },
      {
        slug: "chute-rome",
        year: 476,
        title: "La chute de l'Empire romain",
        description: "Après 1 000 ans de grandeur, l'Empire romain d'Occident s'effondre sous les invasions barbares - mais son héritage ne mourra jamais.",
        content: "Depuis des dizaines d'années, des peuples guerriers venus du nord et de l'est - les Wisigoths, les Vandales, les Huns dirigés par le terrible Attila - attaquent les frontières de l'Empire romain. L'empire est trop grand pour être bien défendu, et ses empereurs se succèdent si vite (certains règnent seulement quelques mois avant d'être tués) que tout le monde est perdu. C'est comme si ton équipe de foot changeait de capitaine toutes les semaines !\n\nEn 410, l'impensable se produit : la ville de Rome est pillée pour la première fois depuis 800 ans. Les habitants sont sous le choc - Rome semblait éternelle et invincible ! Finalement, en 476, le chef barbare Odoacre dépose le dernier empereur d'Occident, un jeune homme appelé Romulus Augustule. C'est la fin officielle de l'Empire romain d'Occident. En Orient, l'Empire byzantin, lui, survivra encore 1 000 ans.\n\nLa chute de Rome marque le début du Moyen Âge. Les grandes villes se vident, certaines routes ne sont plus entretenues, et beaucoup de connaissances romaines sont perdues. Mais Rome ne disparaît pas vraiment : son Église catholique continue à unir les Européens, sa langue latine reste celle des savants pendant 1 000 ans, et ses lois inspirent encore nos codes civils aujourd'hui. Rome est tombée, mais son âme a traversé les siècles.",
      },
    ],
  },
  {
    slug: "moyen-age",
    label: "Moyen Âge",
    events: [
      {
        slug: "mahomet-islam",
        year: 622,
        title: "Mahomet fonde l'islam",
        description: "Dans le désert d'Arabie, un marchand reçoit ce qu'il croit être la parole de Dieu et fonde une religion qui rassemblera 2 milliards de personnes.",
        content: "Il y a 1 400 ans, dans la ville de La Mecque en Arabie, un homme de 40 ans appelé Mahomet dit avoir reçu des révélations de l'ange Gabriel. Ces messages, qu'il récite à ses proches, forment un livre sacré appelé le Coran. Mahomet prêche une idée simple mais puissante : il n'y a qu'un seul Dieu, Allah, et tous les êtres humains sont égaux devant lui. À une époque où les riches écrasent les pauvres, ce message attire beaucoup de monde.\n\nMais les chefs de La Mecque n'aiment pas du tout ce discours d'égalité - il menace leur pouvoir. En 622, Mahomet et ses fidèles doivent fuir en catastrophe vers la ville de Médine : c'est l'Hégire, le grand départ qui marque le début du calendrier musulman. De Médine, Mahomet organise sa communauté et finit par revenir conquérir La Mecque en 630, sans presque une goutte de sang versée.\n\nAprès la mort de Mahomet en 632, l'islam se répand à une vitesse stupéfiante : en moins de 100 ans, il couvre l'Arabie, l'Égypte, l'Afrique du Nord, l'Espagne et la Perse. Aujourd'hui, l'islam est la deuxième religion du monde avec 2 milliards de croyants. Les savants musulmans du Moyen Âge ont préservé et enrichi les connaissances grecques en mathématiques, astronomie et médecine - des connaissances qui sont ensuite revenues en Europe et ont alimenté la Renaissance.",
      },
      {
        slug: "vikings",
        year: 793,
        title: "Les Vikings attaquent l'Europe",
        description: "Des guerriers venus de Scandinavie terrorisent l'Europe sur leurs drakkars, mais sont aussi d'extraordinaires explorateurs et commerçants.",
        content: "En 793, des bateaux étranges à tête de dragon apparaissent au large des côtes d'Angleterre. Des guerriers blonds et barbus, armés de haches et d'épées, débarquent et pillent un monastère sur l'île de Lindisfarne. L'Europe découvre les Vikings ! Pendant deux siècles, ces guerriers venus de Norvège, Suède et Danemark vont semer la terreur dans toute l'Europe. Les moines tremblent en priant : 'Seigneur, protège-nous de la fureur des Normands !'\n\nMais les Vikings ne sont pas seulement des pillards. Ce sont aussi des marins extraordinaires et des explorateurs courageux. Leurs drakkars - des bateaux longs et plats - peuvent naviguer aussi bien en pleine mer que sur les rivières peu profondes. Ils atteignent l'Islande, le Groenland, et même l'Amérique du Nord 500 ans avant Christophe Colomb ! Certains Vikings s'installent en France (les Normands), en Russie, en Angleterre et en Sicile.\n\nLes descendants des Vikings ont profondément marqué l'histoire. Les Normands installés en France deviennent français, se battent en croisade et construisent des cathédrales. En 1066, Guillaume le Conquérant - un descendant de Vikings - conquiert l'Angleterre et mélange le français et l'anglais pour créer la langue anglaise telle qu'on la parle aujourd'hui. Des mots anglais comme 'sky', 'knife' ou 'egg' viennent directement du vieux norrois, la langue des Vikings !",
      },
      {
        slug: "couronnement-charlemagne",
        year: 800,
        title: "Couronnement de Charlemagne",
        description: "Le jour de Noël 800, Charlemagne est couronné empereur d'Occident - un moment qui dessine les premières frontières de l'Europe.",
        content: "Le 25 décembre 800, lors de la messe de Noël à Rome, quelque chose d'inattendu se passe. Le pape Léon III s'approche de Charlemagne, le puissant roi des Francs, et pose une couronne dorée sur sa tête. La foule crie : 'Longue vie à Charles, Auguste, couronné par Dieu !' Charlemagne devient empereur d'Occident, le chef le plus puissant d'Europe depuis la chute de Rome. On dit qu'il était lui-même très surpris par ce geste du pape !\n\nCharlemagne règne sur un empire immense qui couvre l'actuelle France, l'Allemagne, l'Italie du Nord, la Belgique et une partie de l'Espagne. Malgré le fait qu'il ne sait peut-être pas lire, il adore les savoirs. Il rassemble à sa cour les meilleurs professeurs et savants d'Europe, crée des écoles dans tout son empire et oblige les futurs prêtres à apprendre à lire. C'est la 'renaissance carolingienne' - l'Europe recommence à apprendre après des siècles sombres.\n\nAprès la mort de Charlemagne, son empire est partagé entre ses petits-fils. Ce partage, le traité de Verdun en 843, dessine pour la première fois des frontières qui ressemblent à celles de la France et de l'Allemagne d'aujourd'hui. C'est pour cette raison que Charlemagne est souvent appelé 'le père de l'Europe'. Des siècles plus tard, quand les pays européens ont décidé de construire l'Union Européenne, ils se sont souvenus de lui.",
      },
      {
        slug: "guillaume-conquerant",
        year: 1066,
        title: "Guillaume le Conquérant",
        description: "Un duc normand traverse la Manche et conquiert l'Angleterre en une seule bataille, transformant pour toujours la langue et la culture anglaises.",
        content: "En 1066, Guillaume, duc de Normandie (dans l'actuelle France), apprend que le roi d'Angleterre vient de mourir et qu'un autre a pris le trône à sa place. Il est furieux : il pensait que c'était à lui de devenir roi d'Angleterre ! Il rassemble une armée de 10 000 hommes, construit une flotte de bateaux et traverse la Manche avec ses chevaliers normands. C'est l'invasion la plus importante de l'histoire anglaise.\n\nLe 14 octobre 1066, les deux armées se retrouvent à Hastings. La bataille est longue et acharnée. Le roi anglais Harold est tué - selon la légende, d'une flèche dans l'œil - et ses soldats s'enfuient. Guillaume a gagné ! Il est couronné roi d'Angleterre à Noël 1066 dans l'abbaye de Westminster, exactement là où les rois britanniques sont encore couronnés aujourd'hui.\n\nLa conquête normande transforme l'Angleterre de fond en comble. Les nobles français apportent leur langue avec eux. Pendant 300 ans, les rois d'Angleterre parlent français ! Le résultat ? La langue anglaise devient un mélange fascinant de l'ancien anglais (allemanique) et du français normand. Des milliers de mots anglais viennent directement du français : 'beef' (bœuf), 'justice', 'castle' (château). C'est pour ça qu'on dit que l'anglais est la langue la plus riche du monde !",
      },
      {
        slug: "premiere-croisade",
        year: 1096,
        title: "La Première Croisade",
        description: "Des milliers de chevaliers et de pèlerins partent reconquérir Jérusalem, déclenchant deux siècles de guerres religieuses en Terre Sainte.",
        content: "En 1095, le pape Urbain II monte sur une estrade à Clermont, en France, et lance un appel qui fait trembler l'Europe : 'Partez délivrer Jérusalem des mains des Turcs !' La foule répond en criant 'Dieu le veut !' Des milliers de chevaliers cousent une croix rouge sur leur manteau et se préparent à un voyage de plusieurs milliers de kilomètres vers la Terre Sainte. Même des paysans pauvres, des femmes et des enfants se joignent à cette incroyable marche.\n\nAprès trois ans d'une marche épuisante à travers la Turquie et la Syrie - avec des batailles terribles, la famine et les maladies - les croisés arrivent enfin devant Jérusalem en 1099. Après un siège de 5 semaines, ils entrent dans la ville. Ce qui suit est terrible : des milliers d'habitants musulmans et juifs sont tués. Les croisés, épuisés et sous le choc, pleurent et prient devant les lieux saints.\n\nLes croisades ne sont pas qu'une histoire de violence. Ces expéditions créent aussi des échanges extraordinaires entre l'Europe chrétienne et le monde arabe. Les croisés découvrent des épices, des étoffes magnifiques, des mathématiques et des connaissances médicales qu'ils ramènent en Europe. Les Arabes, eux, découvrent les techniques de construction européennes. Ces échanges involontaires enrichissent les deux civilisations et préparent le chemin vers la Renaissance.",
      },
      {
        slug: "construction-notre-dame",
        year: 1163,
        title: "Construction de Notre-Dame de Paris",
        description: "Des milliers d'ouvriers passent 200 ans à bâtir la plus belle cathédrale du monde - un chef-d'œuvre de pierre et de lumière.",
        content: "En 1163, l'évêque de Paris, Maurice de Sully, pose la première pierre d'une cathédrale qui va devenir l'une des plus belles du monde. Construire Notre-Dame prend 200 ans - des générations entières d'ouvriers, de sculpteurs et de verriers travaillent sur ce chantier gigantesque sans jamais le voir terminé. Ces bâtisseurs inventent un nouveau style d'architecture révolutionnaire : le gothique, avec ses grandes arches pointues et ses vitraux colorés qui font entrer la lumière à flots.\n\nLa cathédrale est un vrai défi technique pour l'époque. Comment faire tenir des murs si hauts et si minces, avec d'immenses fenêtres ? Les architectes inventent les arcs-boutants, des sortes de béquilles de pierre en arc qui maintiennent les murs de l'extérieur. Grâce à cette astuce géniale, les murs peuvent être percés d'immenses vitraux multicolores. Quand le soleil brille sur ces vitraux, l'intérieur de la cathédrale devient magique, baigné de lumière rouge, bleue et or.\n\nNotre-Dame a traversé des siècles d'histoire : des révolutions, des guerres, des profanations. En 2019, un incendie terrible l'a ravagée sous les yeux du monde entier. Des millions de personnes ont pleuré en regardant les flammes dévorer sa flèche. Mais elle a été reconstruite grâce à la solidarité internationale. Notre-Dame nous rappelle que les chefs-d'œuvre créés par l'humanité appartiennent à tous les peuples du monde, et que nous avons tous envie de les protéger.",
      },
      {
        slug: "magna-carta",
        year: 1215,
        title: "La Magna Carta",
        description: "Les nobles anglais forcent leur roi à signer un document qui dit que même un roi doit respecter des règles - une idée révolutionnaire.",
        content: "En 1215, le roi Jean d'Angleterre est détesté de tout le monde. Il lève des impôts trop élevés, fait emprisonner des gens sans raison, et décide de tout tout seul, sans consulter personne. Les nobles en ont assez ! Ils forment une armée, prennent Londres, et forcent Jean à les retrouver dans un champ au bord de la Tamise. Là, ils lui mettent un parchemin sous le nez : 'Signe, ou on te chasse !' Jean signe.\n\nCe parchemin s'appelle la Magna Carta, ce qui veut dire 'la Grande Charte' en latin. Il dit des choses révolutionnaires pour l'époque : personne ne peut être emprisonné sans jugement. Le roi lui-même doit respecter les lois. Avant de lever de nouveaux impôts, le roi doit demander l'avis de ses nobles. C'est la première fois dans l'histoire qu'on écrit noir sur blanc que le pouvoir du roi a des limites !\n\nLa Magna Carta est le grand-père de toutes les constitutions et déclarations des droits du monde. Quand les Américains ont rédigé leur Constitution en 1787, ils s'en sont directement inspirés. Quand on parle de 'droits de l'homme', d'habeas corpus (le droit de ne pas être emprisonné sans jugement), de procès équitable - tout cela remonte à ce parchemin signé dans un champ anglais il y a 800 ans. C'est l'une des idées les plus importantes que l'humanité ait jamais eues.",
      },
      {
        slug: "marco-polo",
        year: 1271,
        title: "Marco Polo part pour la Chine",
        description: "Un jeune Vénitien de 17 ans s'engage dans le plus grand voyage de l'histoire médiévale et revient avec des récits qui font rêver l'Europe entière.",
        content: "En 1271, un jeune homme de 17 ans appelé Marco Polo quitte Venise avec son père et son oncle. Leur destination ? La Chine, à l'autre bout du monde, un pays fabuleux dont les Européens ont entendu parler par des marchands mais que personne d'eux n'a jamais vu. Le voyage dure 3 ans : ils traversent la Turquie, l'Iran, l'Afghanistan, le désert de Gobi... un vrai périple d'aventuriers !\n\nQuand il arrive en Chine, Marco Polo est ébloui. L'empire du grand Khan Kubilaï est d'une richesse et d'une organisation que l'Europe ne peut pas imaginer. Il y a des villes immenses, des routes parfaites, des papiers-monnaie (en Europe on n'utilise que des pièces !), des services postaux efficaces, et des technologies que l'Europe n'a pas encore. Marco Polo reste 17 ans en Chine et travaille comme diplomate pour l'Empereur.\n\nQuand il rentre à Venise, personne ne le reconnaît. Il raconte ses aventures dans un livre qui devient le best-seller du Moyen Âge - tout le monde en Europe veut le lire ! Ses descriptions de la Chine, de l'Inde et des épices de l'Orient vont donner des idées à de nombreux explorateurs. Christophe Colomb avait une copie annotée du livre de Marco Polo quand il a traversé l'Atlantique. Sans Marco Polo, peut-être pas de découverte de l'Amérique !",
      },
      {
        slug: "peste-noire",
        year: 1347,
        title: "La Peste Noire",
        description: "Une terrible maladie venue d'Asie tue un tiers des Européens en seulement 6 ans - la plus grande catastrophe sanitaire de l'histoire.",
        content: "En 1347, des bateaux génois arrivent en Sicile avec leurs marins mourants. Ces marins ont le corps couvert de grosses boules noires qui suintent du sang et du pus. Ils meurent en quelques jours. C'est la peste bubonique, une maladie mortelle transmise par les puces qui vivent sur les rats. En quelques mois, elle se répand comme un feu de forêt dans toute l'Europe - les bateaux de commerce la transportent de port en port.\n\nPersonne ne comprend ce qui se passe. Les médecins sont impuissants, les prières ne servent à rien. Les familles abandonnent leurs malades, les villages se vident, les corps s'entassent dans les rues. En 6 ans, la Peste Noire tue entre 25 et 50 millions de personnes en Europe - c'est comme si un Européen sur trois mourrait ! Des villes entières disparaissent. C'est la catastrophe la plus terrible que l'humanité ait jamais vécue avant les guerres mondiales.\n\nParadoxalement, la Peste Noire va provoquer des changements étonnants. Comme il y a beaucoup moins de travailleurs, ceux qui survivent peuvent exiger de meilleures conditions et de meilleurs salaires. Les paysans gagnent du pouvoir face aux seigneurs. L'Église, incapable d'expliquer ou d'arrêter la maladie, perd de sa crédibilité. Tout cela va accélérer la fin du Moyen Âge et l'arrivée d'un nouveau monde : la Renaissance. La catastrophe a semé les graines du renouveau.",
      },
      {
        slug: "jeanne-d-arc",
        year: 1429,
        title: "Jeanne d'Arc sauve la France",
        description: "Une jeune paysanne de 17 ans entend des voix célestes et galvanise une armée entière pour sauver la France de l'occupation anglaise.",
        content: "En 1429, la France est dans une situation désespérée. Les Anglais occupent presque tout le pays depuis des années, et les soldats français ont oublié comment gagner. C'est alors qu'apparaît une jeune fille de 17 ans, Jeanne, venue d'un village de Lorraine appelé Domrémy. Elle dit avoir entendu les voix de saints qui lui commandent de chasser les Anglais et de faire couronner le prince Charles comme roi de France. Tout le monde pense qu'elle est folle - jusqu'à ce qu'elle convainque le prince de lui confier une armée.\n\nCe qui se passe ensuite tient du miracle. En quelques semaines, Jeanne d'Arc, vêtue d'une armure blanche et portant un étendard blanc orné de fleurs de lys, galvanise les soldats démoralisés. Elle lève le siège d'Orléans en 9 jours, conduit l'armée de victoire en victoire, et accompagne Charles jusqu'à Reims pour son sacre. Les Anglais, stupéfaits, commencent à croire que Jeanne est une sorcière envoyée contre eux.\n\nMalheureusement, Jeanne est capturée par les Bourguignons, alliés des Anglais, et vendue à ces derniers. Jugée pour hérésie et sorcellerie dans un procès truqué, elle est brûlée vive à Rouen en 1431. Elle a 19 ans. Vingt-cinq ans plus tard, un nouveau procès la réhabilite. Canonisée sainte en 1920, Jeanne d'Arc est aujourd'hui le symbole de la France courageuse face à l'oppression. Son histoire prouve qu'une seule personne déterminée peut changer le cours de l'histoire.",
      },
    ],
  },
  {
    slug: "renaissance",
    label: "Renaissance",
    events: [
      {
        slug: "imprimerie-gutenberg",
        year: 1450,
        title: "L'imprimerie de Gutenberg",
        description: "Johannes Gutenberg invente la presse à imprimer et révolutionne la diffusion du savoir - c'est l'internet du XVe siècle !",
        content: "Avant 1450, si tu voulais un livre, il fallait le payer très cher car des moines le copiaient à la main - un travail de plusieurs mois ! Seuls les très riches pouvaient s'offrir des livres. C'est alors que Johannes Gutenberg, un orfèvre de Mayence en Allemagne, a une idée de génie : créer des petites lettres en métal qu'on peut assembler pour former des mots, les enduire d'encre et les presser sur du papier. Sa première grande impression ? La Bible, vers 1455.\n\nL'effet est immédiat et révolutionnaire. Avec la presse de Gutenberg, on peut imprimer des centaines de copies d'un livre en quelques jours, là où un moine en copiait une seule en plusieurs mois. Les livres deviennent beaucoup moins chers. En 50 ans, plus de 15 millions de livres circulent en Europe - plus que tout ce qui avait été produit depuis l'Antiquité ! Les idées se répandent à une vitesse que le monde n'a jamais connue.\n\nL'imprimerie de Gutenberg est l'internet du XVe siècle : elle brise le monopole de l'Église sur le savoir, permet à des idées comme celles de Luther ou de Copernic de toucher des milliers de lecteurs en quelques semaines, et nourrit une soif d'apprendre et de débattre qui va transformer l'Europe. Sans l'imprimerie, pas de Réforme protestante, pas de Révolution scientifique, pas de Lumières. Gutenberg a libéré les idées et les a rendues accessibles à tous.",
      },
      {
        slug: "chute-constantinople",
        year: 1453,
        title: "La chute de Constantinople",
        description: "La capitale de l'Empire byzantin tombe après 1 000 ans de résistance - et ses savants fuient vers l'Occident, apportant la Renaissance avec eux.",
        content: "Constantinople est la plus belle ville du monde médiéval - c'est la capitale de l'Empire byzantin, héritier direct de Rome, avec ses palais dorés, ses bibliothèques remplies de manuscrits grecs et ses immenses murailles. En 1453, le jeune sultan ottoman Mehmed II, 21 ans, assiège la ville avec une armée de 100 000 hommes et - chose incroyable pour l'époque - des canons gigantesques. Les murailles qui ont résisté 1 000 ans s'effondrent en quelques semaines.\n\nLe 29 mai 1453, les soldats ottomans entrent dans Constantinople. Le dernier empereur byzantin, Constantin XI, préfère mourir au combat plutôt que de capituler. La ville est pillée pendant trois jours. Des milliers de manuscrits grecs anciens - les œuvres de Platon, Aristote, Homère - sont brûlés ou volés. Mehmed II fait de Constantinople sa nouvelle capitale et la rebaptise Istanbul.\n\nLa chute de Constantinople a une conséquence inattendue : des centaines de savants byzantins fuient vers l'Italie avec leurs précieux manuscrits grecs dans leurs bras. Ces textes anciens, dont beaucoup étaient inconnus en Occident, relancent l'étude de la philosophie, des mathématiques et de la littérature grecques. Les savants byzantins déclenchent ainsi involontairement la Renaissance italienne ! Un désastre pour Byzance devient une chance pour l'Occident.",
      },
      {
        slug: "decouverte-amerique",
        year: 1492,
        title: "La découverte de l'Amérique",
        description: "Christophe Colomb traverse l'Atlantique vers l'ouest et atteint un continent dont les Européens ignoraient totalement l'existence.",
        content: "En 1492, Christophe Colomb, un navigateur génois au service de l'Espagne, est convaincu d'une chose que tout le monde juge folle : en naviguant vers l'ouest, on peut atteindre les Indes et leurs épices précieuses. Après avoir convaincu la reine Isabelle d'Espagne de financer son expédition, il part avec trois petits bateaux et 90 hommes. Après 70 jours de navigation en plein Atlantique - une éternité sans voir la terre - l'équipage commence à paniquer. Puis, le 12 octobre 1492, un marin crie 'Terre !'\n\nColomb a découvert les Bahamas. Convaincu d'être aux Indes, il appelle les habitants 'Indiens' - une erreur qui reste dans le vocabulaire jusqu'à aujourd'hui ! Il ignore qu'il vient de mettre le pied sur un continent inconnu peuplé de 50 à 100 millions d'habitants : Aztèques, Incas, Mayas et centaines d'autres peuples. En quelques décennies, les Espagnols conquièrent ces empires, souvent à cause des maladies européennes - variole, rougeole - contre lesquelles les Amérindiens n'ont aucune défense.\n\n1492 change le monde des deux côtés de l'Atlantique. De l'Amérique arrive en Europe : la pomme de terre, le maïs, la tomate, le chocolat, le piment, la vanille - des aliments qui transforment complètement la cuisine européenne ! Imagine la cuisine italienne sans tomates, ou l'Europe sans pommes de terre... L'Amérique nous a tout donné ça. En échange, l'Europe apporte ses maladies, ses armes et ses religions. C'est le début d'une mondialisation qui ne s'arrêtera plus jamais.",
      },
      {
        slug: "vasco-de-gama",
        year: 1498,
        title: "Vasco de Gama ouvre la route des Indes",
        description: "Le navigateur portugais contourne l'Afrique et ouvre une nouvelle route maritime vers les épices de l'Inde - sans passer par les territoires arabes.",
        content: "En 1498, le navigateur portugais Vasco de Gama réalise quelque chose qu'on croyait impossible : contourner toute l'Afrique par le sud pour atteindre l'Inde par la mer. Avec 4 bateaux et 170 hommes, il part de Lisbonne, longe les côtes africaines, passe le cap de Bonne-Espérance (la pointe la plus au sud de l'Afrique) dans des tempêtes terribles, remonte la côte est de l'Afrique et arrive enfin à Calicut en Inde, 10 mois et demi après son départ !\n\nPourquoi était-ce si important ? Parce que les épices - poivre, cannelle, muscade, gingembre - valaient plus cher que l'or en Europe. Ces épices venaient d'Asie mais les routes terrestres étaient contrôlées par les marchands arabes qui prenaient des prix exorbitants. En ouvrant une route maritime directe, le Portugal peut maintenant acheter les épices à la source et les revendre beaucoup moins cher en Europe, devenant immensément riche.\n\nLa route de Vasco de Gama transforme l'économie mondiale. Lisbonne devient la capitale commerciale de l'Europe. Le Portugal construit un empire maritime gigantesque qui s'étend de l'Afrique au Brésil, en passant par l'Inde et l'Asie du Sud-Est. Cette domination du commerce maritime par les Européens va durer 400 ans. Et la carte du monde que tu connais, avec ses grandes routes maritimes qui relient tous les continents, est directement héritée des explorateurs portugais comme Vasco de Gama.",
      },
      {
        slug: "leonard-de-vinci",
        year: 1503,
        title: "Léonard de Vinci peint la Joconde",
        description: "Le génie universel de la Renaissance crée en secret le tableau le plus célèbre et le plus mystérieux du monde.",
        content: "Léonard de Vinci est l'homme le plus curieux du monde. Peintre, sculpteur, architecte, ingénieur, musicien, anatomiste - il veut tout comprendre, tout maîtriser. Ses carnets de notes débordent de schémas de machines volantes, de sous-marins, de chars d'assaut et de ponts - des inventions qui ne seront réalisées que des siècles plus tard. Il passe des nuits entières à disséquer des cadavres en secret pour comprendre le corps humain. Pour lui, l'art et la science ne font qu'un.\n\nEntre 1503 et 1519, il travaille à un portrait de femme - probablement Lisa Gherardini, femme d'un riche marchand florentin. Pour peindre ce tableau qu'on appellera la Joconde, il invente une technique révolutionnaire : le sfumato, qui consiste à estomper les contours comme dans un rêve, donnant à la peinture une profondeur et une douceur jamais vues. Le sourire de la Joconde, légèrement ambigu, semble changer selon l'angle où on la regarde.\n\nAujourd'hui, la Joconde est exposée au Louvre à Paris et attire 10 millions de visiteurs chaque année - c'est le tableau le plus visité du monde ! Elle est aussi le tableau le plus reproduit, le plus imité et le plus commenté de toute l'histoire de l'art. Volée en 1911, retrouvée deux ans plus tard, elle est considérée comme inestimable. La Joconde nous montre que la perfection technique et le mystère peuvent créer quelque chose d'immortel.",
      },
      {
        slug: "michel-ange-sixtine",
        year: 1512,
        title: "Michel-Ange peint la chapelle Sixtine",
        description: "Un génie obstiné passe 4 ans allongé sur un échafaudage à peindre le plus grand chef-d'œuvre religieux de l'humanité.",
        content: "En 1508, le pape Jules II convoque Michel-Ange et lui donne une mission : peindre le plafond de la chapelle Sixtine, à Rome. Michel-Ange proteste - il est sculpteur, pas peintre ! Mais le pape insiste. Alors Michel-Ange accepte et décide de faire quelque chose d'extraordinaire : au lieu d'une simple décoration, il va peindre toute la Genèse, le premier livre de la Bible, avec des dizaines de scènes et des centaines de personnages. Seul, presque sans aide.\n\nDurant 4 ans, Michel-Ange travaille allongé sur un échafaudage en bois à 20 mètres de hauteur, la tête penchée en arrière, de la peinture qui lui tombe dans les yeux. Il refuse que quiconque voie son travail avant qu'il soit terminé. Quand il descend enfin de son échafaudage en 1512, le résultat est stupéfiant : 500 mètres carrés de fresques, 300 personnages aux corps puissants et expressifs, avec au centre la scène la plus reproduite de l'art occidental - Dieu tendant le doigt vers Adam pour lui donner la vie.\n\nLa chapelle Sixtine est aujourd'hui l'œuvre d'art la plus visitée du monde (avec 7 millions de visiteurs par an au Vatican). Mais pour Michel-Ange, ce n'était que le début. Il sculpta ensuite le Moïse et la Pietà, et fut chargé de superviser la construction de la basilique Saint-Pierre. Il travailla jusqu'à ses 88 ans ! Sa vie entière nous montre que la passion pour ce qu'on fait peut permettre des choses extraordinaires.",
      },
      {
        slug: "reforme-protestante",
        year: 1517,
        title: "La Réforme protestante de Luther",
        description: "Un moine allemand cloue 95 critiques sur une porte d'église et déclenche une révolution religieuse qui fracture l'Europe pour des siècles.",
        content: "En 1517, Martin Luther, un moine allemand, est furieux. L'Église catholique vend des 'indulgences' - des papiers qui promettent que tes péchés seront pardonnés si tu paies assez cher. Pour Luther, c'est une arnaque scandaleuse : le pardon de Dieu ne peut pas s'acheter ! Il écrit 95 arguments contre cette pratique et, selon la légende, les affiche sur la porte de l'église de Wittenberg. Grâce à l'imprimerie de Gutenberg, ses idées se répandent en quelques semaines dans toute l'Europe.\n\nLe pape ordonne à Luther de se taire. Luther refuse et brûle publiquement la lettre du pape ! En 1521, convoqué devant l'empereur Charles Quint, il prononce des mots qui resteront célèbres : 'Me voici, je ne peux pas faire autrement.' Il est excommunié (exclu de l'Église) mais des princes allemands le protègent. Luther traduit alors la Bible en allemand pour que tout le monde puisse la lire sans passer par les prêtres - une idée révolutionnaire.\n\nLa Réforme de Luther brise l'unité religieuse de l'Europe en deux : d'un côté les catholiques, de l'autre les protestants. Cela déclenche des guerres de religion terribles pendant 130 ans. Mais la Réforme produit aussi des effets positifs : elle pousse l'Église catholique à se réformer, stimule l'éducation (Luther veut que tout le monde sache lire pour lire la Bible) et encourage la liberté de conscience - l'idée que chacun peut croire ce qu'il veut. C'est une petite graine qui donnera naissance à la liberté de religion.",
      },
      {
        slug: "magellan",
        year: 1519,
        title: "Magellan fait le tour du monde",
        description: "Pour la première fois dans l'histoire, une expédition fait le tour complet de la Terre - prouvant définitivement que notre planète est ronde.",
        content: "En 1519, le navigateur portugais Ferdinand de Magellan part d'Espagne avec 5 bateaux et 270 hommes avec un objectif fou : faire le tour complet de la Terre par l'ouest pour atteindre les îles aux épices. Beaucoup pensent que c'est un voyage sans retour. Et ils ont un peu raison... Après avoir traversé l'Atlantique, Magellan passe par un détroit terrible au bout de l'Amérique du Sud (qui porte aujourd'hui son nom) et entre dans un océan si calme qu'il l'appelle 'Pacifique'.\n\nLe voyage du Pacifique dure 4 mois terribles sans voir la terre. Les marins mangent du cuir bouilli, des rats et de la sciure pour survivre. Quand ils atteignent les Philippines, Magellan est tué dans un combat avec des guerriers locaux. Mais son second, Elcano, prend le commandement. Avec un seul bateau qui prend l'eau et 18 hommes épuisés (sur 270 au départ !), il réussit à rentrer en Espagne en septembre 1522.\n\nCe voyage de 3 ans change la vision du monde pour toujours. La Terre est définitivement ronde - on peut en faire le tour ! L'océan Pacifique, inconnu des Européens, est cartographié pour la première fois. L'expédition de Magellan-Elcano est l'équivalent pour l'époque d'un voyage sur la Lune : une aventure terrifiante vers l'inconnu qui repousse les limites du possible et ouvre un monde entièrement nouveau.",
      },
      {
        slug: "copernic-heliocentrisme",
        year: 1543,
        title: "Copernic et la révolution du cosmos",
        description: "Un astronome polonais ose dire que c'est la Terre qui tourne autour du Soleil - et non l'inverse - renversant 1 500 ans de certitudes.",
        content: "Depuis 1 500 ans, tout le monde est convaincu que la Terre est au centre de l'univers, et que le Soleil, la Lune et les étoiles tournent autour d'elle. C'est ce que disait le savant grec Ptolémée, et l'Église en a fait une vérité divine. Mais Nicolas Copernic, un astronome polonais, observe le ciel nuit après nuit et quelque chose cloche : les planètes ne se déplacent pas comme elles devraient si la Terre était au centre. Il en tire une conclusion terrifiante : c'est la Terre qui tourne autour du Soleil !\n\nCopernic est tellement conscient du scandale que sa théorie va provoquer qu'il attend d'être mourant pour la publier. Le livre sort en 1543, l'année de sa mort. L'Église met du temps à réagir, mais 73 ans plus tard, elle place le livre à l'Index - la liste des livres interdits. Galilée, qui défend Copernic avec son télescope, est condamné par l'Inquisition en 1633 et forcé de se rétracter. Mais la vérité ne peut pas être arrêtée.\n\nLa révolution de Copernic est la plus grande révolution intellectuelle de l'histoire humaine. Elle dit quelque chose de vertigineux : nous, les humains, ne sommes pas au centre de l'univers. La Terre n'est qu'une petite planète qui tourne autour d'une étoile ordinaire, parmi des milliards d'autres. Cette idée, si difficile à accepter au XVIe siècle, est la base de toute l'astronomie et de la physique modernes. Sans Copernic, pas de Newton, pas d'Einstein, pas de fusées spatiales.",
      },
      {
        slug: "shakespeare",
        year: 1599,
        title: "Shakespeare et le théâtre Globe",
        description: "Le plus grand écrivain de la langue anglaise crée des pièces qui parlent de l'amour, de la jalousie et du pouvoir - toujours aussi vraies 400 ans plus tard.",
        content: "En 1599, à Londres, William Shakespeare et sa troupe construisent un théâtre en bois qu'ils appellent le Globe. Ce théâtre circulaire peut accueillir 3 000 spectateurs debout autour de la scène. Riches et pauvres se mélangent pour voir les pièces de Shakespeare : des histoires passionnantes de rois, de guerriers, d'amoureux et de fous. À une époque sans télévision ni cinéma, le théâtre est le divertissement numéro un - et Shakespeare est la superstar de son époque.\n\nShakespeare écrit 37 pièces en tout. Roméo et Juliette (le plus célèbre histoire d'amour impossible), Hamlet (un prince qui veut venger son père assassiné), Macbeth (un général qui devient fou après avoir tué le roi), Le Songe d'une nuit d'été (une comédie magique pleine de fées)... Chacune de ses pièces plonge dans les émotions les plus profondes des humains : l'amour, la jalousie, l'ambition, la peur de la mort. Des sentiments que tout le monde comprend, dans n'importe quelle époque.\n\nAujourd'hui, 400 ans après sa mort, Shakespeare est l'écrivain le plus joué du monde. Ses pièces sont traduites dans plus de 100 langues. Des dizaines de films, de comédies musicales et de séries s'inspirent de ses histoires (Le Roi Lion est inspiré de Hamlet !). Et des milliers de mots et d'expressions que tu utilises viennent de ses pièces : 'break the ice' (briser la glace), 'heart of gold' (cœur d'or), 'fashionable' (à la mode). Shakespeare a littéralement inventé des mots !",
      },
    ],
  },
  {
    slug: "revolution-industrielle",
    label: "Rév. Industrielle",
    events: [
      {
        slug: "machine-vapeur-watt",
        year: 1769,
        title: "La machine à vapeur de Watt",
        description: "James Watt invente une machine révolutionnaire qui transforme la vapeur d'eau en mouvement - et déclenche la révolution industrielle.",
        content: "Avant James Watt, toute l'énergie du monde venait des muscles : des humains, des chevaux, des bœufs. Ou bien du vent dans les voiles des bateaux, ou de l'eau des rivières qui fait tourner les moulins. Mais en 1769, cet ingénieur écossais perfectionne une machine qui change tout : la machine à vapeur. En chauffant de l'eau, on crée de la vapeur, et cette vapeur pousse un piston qui fait tourner des roues. L'énergie du charbon se transforme en mouvement mécanique - sans muscles !\n\nL'effet est immédiat. Les mines peuvent maintenant pomper l'eau beaucoup plus profondément et extraire davantage de charbon. Les usines textiles remplacent les tisserands à la main par des machines qui produisent 100 fois plus vite. Les locomotives à vapeur tirent des trains qui transportent des marchandises et des personnes à des vitesses jamais vues. En 50 ans, le monde change plus qu'il n'a changé en 500 ans auparavant.\n\nLa machine à vapeur de Watt lance la révolution industrielle qui transforme complètement la société. Des millions de paysans quittent leurs villages pour aller travailler dans les usines des grandes villes. Manchester, Birmingham, Lyon deviennent de gigantesques cités ouvrières. Les conditions sont souvent terribles : 12 à 16 heures de travail par jour, des enfants au travail dès 6 ans, des quartiers misérables. Mais cette révolution crée aussi des richesses immenses et accouche lentement de nos droits du travail, de nos retraites et de nos congés payés.",
      },
      {
        slug: "independance-americaine",
        year: 1776,
        title: "L'indépendance des États-Unis",
        description: "Treize colonies britanniques déclarent leur indépendance et inventent une nouvelle façon de gouverner un pays : la démocratie républicaine.",
        content: "En 1776, les treize colonies britanniques d'Amérique du Nord sont épuisées par les impôts que leur impose l'Angleterre - et surtout furieuses de ne pas avoir de représentants au Parlement anglais. 'No taxation without representation !' (Pas d'impôts sans représentation !) crie-t-on dans les rues. Le 4 juillet 1776, les représentants des colonies signent la Déclaration d'Indépendance, rédigée par Thomas Jefferson. Cette déclaration proclame que 'tous les hommes sont créés égaux' et ont droit à la 'vie, la liberté et la recherche du bonheur'.\n\nS'ensuit une guerre de 7 ans contre la puissante armée britannique. Le général George Washington, avec l'aide de la France (qui envoie ses meilleurs soldats et son argent), résiste à toutes les attaques. En 1783, l'Angleterre reconnaît l'indépendance des États-Unis. C'est une victoire incroyable - une armée de volontaires a battu la première puissance militaire du monde ! En 1787, les États-Unis se dotent d'une Constitution révolutionnaire qui sépare les pouvoirs en trois (exécutif, législatif, judiciaire) pour éviter qu'une seule personne concentre tout le pouvoir.\n\nLes États-Unis deviennent le premier exemple moderne d'une démocratie républicaine fédérale - un modèle qui inspire les révolutions européennes et que des dizaines de pays vont copier. La Déclaration d'Indépendance américaine, avec ses idéaux d'égalité et de liberté, reste l'un des textes les plus influents de l'histoire humaine. Même si ces idéaux ont mis longtemps à s'appliquer à tous les Américains (les Noirs étaient encore esclaves !), ils ont posé les fondements d'un monde plus juste.",
      },
      {
        slug: "revolution-francaise",
        year: 1789,
        title: "La Révolution française",
        description: "Le peuple français renverse la monarchie et invente les idées de liberté, d'égalité et de fraternité qui inspirent encore le monde entier.",
        content: "En 1789, la France est à bout. Le roi Louis XVI dépense des fortunes tandis que le peuple meurt de faim. Les nobles et le clergé ne paient pas d'impôts, mais les pauvres en paient énormément. Et les idées des philosophes des Lumières - Voltaire, Rousseau - circulent partout, disant que le peuple a le droit de se gouverner lui-même. Le 14 juillet 1789, des Parisiens furieux prennent d'assaut la forteresse de la Bastille, symbole de l'oppression royale. La Révolution a commencé !\n\nEn quelques années, tout change à une vitesse folle. La féodalité est abolie. La Déclaration des droits de l'homme et du citoyen est proclamée. Le roi Louis XVI et sa reine Marie-Antoinette sont guillotinés en 1793. Mais la Révolution dévore ses propres enfants : Robespierre, qui voulait une France parfaite et pure, fait guillotiner 17 000 personnes en moins d'un an pendant la Terreur. Finalement, un jeune général nommé Napoléon Bonaparte prend le pouvoir en 1799.\n\nLa Révolution française exporte ses idées dans le monde entier. 'Liberté, Égalité, Fraternité' - ces trois mots deviennent la devise de la France et inspirent des révolutions dans toute l'Europe et en Amérique latine. Nos idées modernes sur les droits de l'homme, la séparation de l'Église et de l'État, la citoyenneté et la démocratie viennent en grande partie de 1789. Même les drapeaux tricolores de nombreux pays (Italie, Roumanie, Belgique...) imitent le drapeau bleu-blanc-rouge né à cette époque.",
      },
      {
        slug: "napoleon-empereur",
        year: 1804,
        title: "Napoléon se couronne Empereur",
        description: "Le général le plus brillant de l'époque prend le pouvoir en France et conquiert toute l'Europe - avant de tout perdre en 10 ans.",
        content: "Le 2 décembre 1804, dans la cathédrale Notre-Dame de Paris, une scène incroyable se produit. Le pape Pie VII est venu de Rome pour couronner Napoléon Bonaparte emperor des Français. Mais au moment où le pape s'apprête à poser la couronne sur sa tête, Napoléon lui prend des mains et se couronne lui-même ! Ce geste dit tout : Napoléon ne reconnaît aucune autorité au-dessus de la sienne. Né en Corse d'une famille modeste, il est devenu l'homme le plus puissant d'Europe à 35 ans.\n\nNapoléon est un génie militaire hors du commun. En 10 ans, il bat les armées de presque toute l'Europe - Autriche, Prusse, Russie, Espagne - et place ses frères et généraux sur les trônes de toute l'Europe. Mais Napoléon n'est pas seulement un conquérant. En France, il crée le Code civil (un ensemble de lois claires qui organisent encore notre société), les lycées, la Légion d'honneur, la Banque de France. Il modernise le pays de fond en comble.\n\nMais Napoléon fait des erreurs fatales. L'invasion de la Russie en 1812 se transforme en désastre : son armée de 600 000 hommes est détruite par l'hiver russe. Battu à Waterloo en 1815, il est exilé sur l'île de Sainte-Hélène où il mourra 6 ans plus tard. Sa vie est un roman extraordinaire : du petit Corse méconnu au maître de l'Europe, puis à la solitude d'une île perdue dans l'Atlantique. Le Code civil qu'il a créé est toujours en vigueur dans 40 pays du monde aujourd'hui.",
      },
      {
        slug: "waterloo",
        year: 1815,
        title: "La bataille de Waterloo",
        description: "La dernière grande bataille de Napoléon se termine par une défaite qui remodèle l'Europe et crée un ordre de paix qui durera un siècle.",
        content: "Le 18 juin 1815, dans un champ boueux près de Waterloo en Belgique, deux armées s'affrontent pour décider du sort de l'Europe. D'un côté, Napoléon avec 72 000 soldats français. De l'autre, le duc de Wellington commandant les forces britanniques et alliées, bientôt rejointes par les Prussiens. Napoléon est revenu d'exil depuis seulement 100 jours et veut reprendre le pouvoir. Cette bataille va tout décider en quelques heures.\n\nPendant des heures, les deux armées s'affrontent dans un carnage terrible. Napoléon attend la fin des pluies pour attaquer - une erreur qui lui sera fatale. Quand ses fameux carrés d'infanterie chargent la colline tenue par Wellington, ils sont accueillis par un feu nourri. Puis les Prussiens arrivent sur les flancs français. La déroute est totale : en quelques minutes, l'armée napoléonienne s'enfuit dans le chaos. C'est fini pour Napoléon.\n\nAprès Waterloo, les vainqueurs se réunissent au Congrès de Vienne pour redessinier la carte de l'Europe. Ils créent un système d'équilibre entre les grandes puissances qui va maintenir une paix relative en Europe pendant presque 100 ans - jusqu'en 1914 et la Première Guerre mondiale. Le mot 'Waterloo' est entré dans toutes les langues pour désigner une défaite totale et définitive. Même une chanson du groupe ABBA porte ce nom ! Une bataille qui a changé le monde garde son écho jusqu'à nos jours.",
      },
      {
        slug: "printemps-peuples",
        year: 1848,
        title: "Le Printemps des peuples",
        description: "En 1848, des révolutions éclatent dans toute l'Europe en même temps - une vague de liberté et de nationalisme qui fait trembler les trônes.",
        content: "En février 1848, une révolution éclate à Paris et renverse la monarchie. L'étincelle met le feu à toute l'Europe : en quelques semaines, des soulèvements explosent à Vienne, Budapest, Berlin, Prague, Milan, Rome... C'est le 'Printemps des peuples', la plus grande vague révolutionnaire du XIXe siècle. Deux forces se combinent : le libéralisme (les gens veulent des constitutions et des libertés) et le nationalisme (les peuples veulent former leur propre pays). C'est aussi l'année où Karl Marx et Friedrich Engels publient le Manifeste Communiste.\n\nLes révolutionnaires de 1848 rêvent d'un monde plus juste, avec des élections libres, la liberté de la presse, et des pays unifiés pour les Allemands, les Italiens, les Hongrois. Pendant quelques mois, tout semble possible. Mais les armées des empereurs autrichien et russe reprennent le dessus, une à une. Les révolutions sont écrasées dans le sang. Les révolutionnaires sont emprisonnés, fusillés ou exilés. L'ordre ancien est restauré... en apparence.\n\nCar les idées de 1848 ne meurent pas. L'unification de l'Italie (1861) et de l'Allemagne (1871), l'abolition du servage en Russie, le droit de vote universel masculin en France, l'essor des syndicats ouvriers - tout cela sont les enfants tardifs du Printemps des peuples. Les révolutions de 1848 ont semé des graines qui ont fleuri 10, 20 ou 30 ans plus tard. Elles nous apprennent que les idées de liberté et de justice ne peuvent jamais être complètement étouffées.",
      },
      {
        slug: "darwin-evolution",
        year: 1859,
        title: "Darwin et la théorie de l'évolution",
        description: "Un naturaliste anglais publie une idée révolutionnaire : toutes les espèces vivantes, y compris les humains, ont évolué à partir d'ancêtres communs.",
        content: "Charles Darwin est un naturaliste anglais passionné par les animaux. De 1831 à 1836, il fait le tour du monde sur un bateau appelé le Beagle et observe des milliers d'espèces. Aux îles Galápagos (dans le Pacifique), il remarque quelque chose d'étrange : les pinsons ont des becs différents selon les îles, parfaitement adaptés à la nourriture disponible. Cette observation lui donne une idée révolutionnaire qu'il développe pendant 20 ans avant d'oser la publier.\n\nEn 1859, Darwin publie 'De l'Origine des espèces'. Son idée ? Toutes les espèces vivantes descendent d'ancêtres communs et évoluent lentement par 'sélection naturelle' : les individus les mieux adaptés à leur environnement survivent et se reproduisent, transmettant leurs avantages à leurs enfants. Sur des millions d'années, de petites adaptations créent de nouvelles espèces. Et oui, les humains aussi ont évolué - nous partageons des ancêtres communs avec les singes.\n\nLa théorie de Darwin provoque un scandale immense. L'Église crie au blasphème : comment ose-t-il dire que l'homme descend du singe et non de Dieu ? Des caricatures de Darwin en singe envahissent les journaux. Mais aujourd'hui, l'évolution est le fondement de toute la biologie moderne. Grâce à Darwin, on comprend pourquoi les virus mutent, comment résistance aux antibiotiques se développe, et comment adapter les cultures aux changements climatiques. C'est l'une des découvertes scientifiques les plus importantes de l'histoire humaine.",
      },
      {
        slug: "canal-suez",
        year: 1869,
        title: "Ouverture du canal de Suez",
        description: "Un canal de 160 km creusé à travers l'Égypte relie la Méditerranée à la mer Rouge et révolutionne le commerce mondial.",
        content: "En 1869, après 10 ans de travaux gigantesques, un canal de 160 kilomètres est creusé à travers le désert égyptien pour relier la mer Méditerranée à la mer Rouge. C'est l'ingénieur français Ferdinand de Lesseps qui a porté ce projet titanesque. Pour creuser ce canal dans le sable et le roc, des dizaines de milliers d'ouvriers égyptiens ont travaillé dans des conditions épuisantes, souvent forcés par les autorités. C'est une prouesse technique spectaculaire pour l'époque.\n\nLe canal de Suez révolutionne le commerce mondial. Avant, les bateaux devaient contourner tout le continent africain pour aller de l'Europe vers l'Asie - un voyage de plusieurs mois. Avec le canal, le trajet est raccourci de 7 000 kilomètres ! Les bateaux peuvent désormais aller de Londres à Bombay en 3 semaines au lieu de 3 mois. Les échanges commerciaux explosent. L'Europe peut obtenir bien plus facilement le coton indien, le thé de Chine, les épices d'Asie.\n\nLe canal de Suez reste aujourd'hui l'une des voies maritimes les plus importantes du monde. Environ 15 % du commerce mondial l'emprunte chaque jour. En 2021, un porte-conteneurs géant appelé l'Ever Given s'y est coincé en travers pendant 6 jours, paralysant le commerce mondial et montrant à quel point ce petit canal de 160 km est vital pour notre économie mondialisée. Un canal creusé au XIXe siècle continue de faire tourner l'économie du XXIe !",
      },
      {
        slug: "commune-paris",
        year: 1871,
        title: "La Commune de Paris",
        description: "Pendant 72 jours, les ouvriers de Paris gouvernent leur ville avec des idées révolutionnaires - avant d'être écrasés dans un bain de sang.",
        content: "En mars 1871, Paris est à bout. La France vient de perdre une guerre humiliante contre la Prusse (l'ancêtre de l'Allemagne). Les Parisiens ont résisté pendant cinq mois de siège terrible, mangeant des rats et des chats pour survivre. Et voilà que le gouvernement français, réfugié à Versailles, veut reprendre les canons aux Parisiens pour les donner aux Prussiens ! Les Parisiens se révoltent et proclament la Commune - leur propre gouvernement, élu démocratiquement, pour gérer la ville.\n\nPendant 72 jours, la Commune prend des mesures incroyablement modernes pour l'époque : école gratuite et laïque pour tous les enfants, salaire minimum pour les ouvriers, droit de grève, égalité de salaire entre hommes et femmes enseignants, remise des loyers pendant la guerre. Des femmes jouent un rôle important - elles organisent l'aide aux blessés, gèrent des écoles, certaines se battent même avec des fusils. C'est une expérience unique dans l'histoire.\n\nMais l'armée du gouvernement de Versailles attaque Paris. Pendant la 'Semaine Sanglante' (21-28 mai 1871), l'armée française reprend Paris rue par rue dans des combats terribles. Au moins 10 000 Communards sont tués, souvent fusillés sur place sans procès. Des milliers d'autres sont déportés dans les îles du Pacifique. La Commune a échoué, mais elle reste un symbole immense pour tous ceux qui rêvent d'un monde plus juste et plus solidaire.",
      },
      {
        slug: "tour-eiffel",
        year: 1889,
        title: "La Tour Eiffel est inaugurée",
        description: "Une immense tour de fer construite pour une exposition universelle devient le symbole le plus reconnu de Paris et du monde.",
        content: "En 1889, Paris organise une grande exposition universelle pour célébrer le centenaire de la Révolution française. Le gouvernement lance un concours pour créer un monument impressionnant. L'ingénieur Gustave Eiffel propose une tour de fer de 300 mètres - la plus haute construction du monde ! Ses critiques sont nombreux : des artistes et des intellectuels la surnomment 'l'affreuse tour en fer', la 'grippe en métal', le 'chandelier de la rue des Deux-Mondes'. Victor Hugo lui-même proteste !\n\nMalgré les critiques, la construction commence en 1887. 300 ouvriers travaillent nuit et jour pendant 2 ans pour assembler 18 000 pièces de métal avec 2,5 millions de rivets. C'est une prouesse d'ingénierie : la tour est si bien calculée qu'elle oscille seulement de quelques centimètres dans les vents violents. Inaugurée le 31 mars 1889, elle accueille 2 millions de visiteurs pendant l'exposition. Même ses détracteurs commencent à l'admirer.\n\nAujourd'hui, la Tour Eiffel est le monument payant le plus visité du monde avec 7 millions de visiteurs par an. Elle est illuminée chaque nuit en blanc, et étincelle de milliers de points lumineux toutes les heures. L'image de la Tour Eiffel est reconnaissable dans le monde entier comme symbole de Paris et de la France. Ce que ses contemporains détestaient est devenu l'un des trésors les plus aimés de l'humanité. La leçon ? Il ne faut jamais juger une œuvre avant qu'elle soit terminée !",
      },
    ],
  },
  {
    slug: "epoque-moderne",
    label: "Époque Moderne",
    events: [
      {
        slug: "premiere-guerre-mondiale",
        year: 1914,
        title: "La Première Guerre mondiale",
        description: "L'assassinat d'un prince autrichien déclenche la guerre la plus meurtrière que le monde ait jamais connue - 18 millions de morts en 4 ans.",
        content: "Le 28 juin 1914, à Sarajevo (dans l'actuelle Bosnie), l'archiduc François-Ferdinand d'Autriche est assassiné par un jeune nationaliste serbe. Ce qui aurait pu rester un incident régional déclenche une catastrophe mondiale à cause des alliances : l'Autriche attaque la Serbie, la Russie défend la Serbie, l'Allemagne défend l'Autriche, la France et l'Angleterre défendent la Russie. En quelques semaines, toute l'Europe est en guerre. C'est comme si une bagarre dans une cour de récré s'étendait à toute l'école !\n\nCette guerre est différente de toutes celles qui l'ont précédée. Les soldats s'enterrent dans des tranchées - de longs fossés profonds sur des centaines de kilomètres. Ils vivent dans la boue, parmi les rats et les corps de leurs camarades, sous des bombardements incessants. Les nouvelles armes - mitrailleuses, gaz de combat, avions, chars d'assaut - causent des destructions inimaginables. La bataille de Verdun dure 10 mois et fait 700 000 morts pour... zéro kilomètre de terrain gagné.\n\nEn novembre 1918, l'armistice arrête enfin les combats. Le bilan est terrifiant : 18 millions de morts, 4 grands empires effondrés (allemand, austro-hongrois, russe, ottoman), des millions de familles brisées. La carte de l'Europe est redessinée. Mais la paix imposée à l'Allemagne est si humiliante et si sévère qu'elle prépare le terrain de la prochaine guerre. Cette 'Grande Guerre' qu'on croyait la 'der des ders' (la dernière des guerres) sera suivie de la Seconde Guerre mondiale 20 ans plus tard.",
      },
      {
        slug: "revolution-russe",
        year: 1917,
        title: "La Révolution russe",
        description: "Le tsar de Russie est renversé, et les communistes de Lénine prennent le pouvoir - lançant 70 ans d'expérience communiste qui marquera le monde.",
        content: "En 1917, la Russie est épuisée par trois ans de guerre mondiale catastrophique. Des millions de soldats russes sont morts ou blessés. Le peuple meurt de faim. Le tsar Nicolas II, le roi de Russie, gouverne comme si on était encore au Moyen Âge et refuse tout changement. En février 1917, les femmes de Petrograd (Saint-Pétersbourg) descendent dans la rue pour réclamer du pain. La révolution commence - et cette fois, même les soldats rejoignent les manifestants au lieu de les tirer dessus. Le tsar abdique.\n\nMais la révolution ne s'arrête pas là. En octobre 1917, Lénine et ses bolcheviks (communistes) organisent un coup d'État et prennent le pouvoir. Leur programme ? Tout partager : les usines appartiennent aux ouvriers, les terres aux paysans, plus de riches ni de pauvres. C'est la mise en pratique des idées de Karl Marx. L'Union Soviétique est créée en 1922. Staline, qui prend le pouvoir après la mort de Lénine, va construire une dictature sanglante qui fera des millions de victimes.\n\nLa Révolution russe partage le monde en deux pendant 70 ans : d'un côté le monde capitaliste (États-Unis, Europe de l'Ouest), de l'autre le monde communiste (URSS, Chine, Cuba). Cette Guerre Froide entre les deux blocs va dominer toute la politique mondiale jusqu'en 1991. Mais l'expérience communiste soviétique se termine en échec : incapable de produire assez de biens pour ses habitants, l'URSS s'effondre en 1991 sans même qu'une seule bombe soit tirée.",
      },
      {
        slug: "crise-1929",
        year: 1929,
        title: "La grande crise de 1929",
        description: "La Bourse de New York s'effondre en une semaine, déclenchant une catastrophe économique mondiale qui plonge des millions de familles dans la misère.",
        content: "Dans les années 1920, les États-Unis vivent dans l'euphorie. Tout le monde achète des actions en Bourse en espérant s'enrichir rapidement - même des gens ordinaires empruntent de l'argent pour jouer en Bourse. Les prix des actions montent, montent, montent... jusqu'au 24 octobre 1929, le 'Jeudi Noir'. Ce jour-là, les investisseurs paniquent et vendent toutes leurs actions en même temps. Les prix s'effondrent. En quelques jours, des millions de personnes perdent toutes leurs économies. C'est un krach boursier gigantesque.\n\nLa crise se répand à toute l'économie comme une maladie. Les banques font faillite (les gens retirent leur argent en panique, et les banques n'ont plus assez). Les usines ferment car personne n'achète plus rien. Des millions de travailleurs perdent leur emploi. Aux États-Unis, 1 Américain sur 4 se retrouve sans travail ! Des files de milliers de chômeurs attendent devant les soupes populaires pour avoir un repas. Des familles entières dorment dans des baraques en carton dans des campements appelés 'Hoovervilles'.\n\nLa crise de 1929 aura des conséquences terribles. En Allemagne, la misère économique pousse des millions de gens désespérés à voter pour un agitateur qui leur promet un avenir radieux : Adolf Hitler. Sans la crise de 1929, Hitler n'aurait peut-être jamais pris le pouvoir, et la Seconde Guerre mondiale n'aurait peut-être pas eu lieu. La crise de 1929 nous apprend que l'économie n'est pas un jeu : quand elle déraille, ce sont les gens ordinaires qui en payent le prix le plus lourd.",
      },
      {
        slug: "seconde-guerre-mondiale",
        year: 1939,
        title: "La Seconde Guerre mondiale",
        description: "La guerre la plus meurtrière de l'histoire humaine fait 70 millions de morts - dont 6 millions de Juifs exterminés par les nazis.",
        content: "Le 1er septembre 1939, les armées d'Adolf Hitler envahissent la Pologne. L'Allemagne nazie a déjà annexé l'Autriche et la Tchécoslovaquie sans que personne ne réagisse, mais cette fois, l'Angleterre et la France déclarent la guerre. Le monde bascule dans un conflit qui va durer 6 ans et tuer entre 60 et 80 millions de personnes - soit 3 fois la population actuelle de la France. C'est la guerre la plus meurtrière et la plus destructrice que l'humanité ait jamais connue.\n\nLa Shoah est le crime le plus abominable de ce conflit. Le régime nazi, convaincu d'une théorie raciste folle, décide d'exterminer tous les Juifs d'Europe. Des hommes, des femmes et des enfants sont arrêtés, entassés dans des trains, et envoyés dans des camps d'extermination - Auschwitz, Treblinka, Sobibor. Là, la grande majorité est immédiatement gazée et brûlée. En 5 ans, 6 millions de Juifs sont ainsi assassinés - c'est les deux tiers des Juifs d'Europe. Ce génocide industriel est unique dans l'histoire humaine.\n\nEn mai 1945, l'Allemagne capitule. En août, les États-Unis larguent deux bombes atomiques sur les villes japonaises d'Hiroshima et Nagasaki - 200 000 morts en quelques secondes. Le Japon capitule. La guerre est terminée, mais le monde est en ruines. De ces cendres naît un espoir : l'ONU, créée pour que les pays règlent leurs conflits par la discussion plutôt que par la guerre, et la Déclaration universelle des droits de l'homme, pour que plus jamais un tel génocide ne soit possible.",
      },
      {
        slug: "bombe-atomique",
        year: 1945,
        title: "La bombe atomique",
        description: "L'humanité invente l'arme la plus destructrice de son histoire - et entre dans une ère où elle peut s'autodétruire.",
        content: "Le 6 août 1945 à 8h15, un avion américain appelé Enola Gay largue une bombe sur la ville japonaise d'Hiroshima. En une fraction de seconde, une explosion d'une puissance inimaginable ravage la ville. 80 000 personnes meurent instantanément. Des dizaines de milliers d'autres meurent dans les semaines suivantes à cause des radiations. Trois jours plus tard, une deuxième bombe est larguée sur Nagasaki : encore 40 000 morts immédiats. Le Japon capitule. La Seconde Guerre mondiale est terminée.\n\nCette bombe atomique est le résultat du 'Projet Manhattan', un programme secret américain qui a réuni les plus grands physiciens du monde - dont beaucoup étaient des réfugiés juifs ayant fui l'Europe nazie. En moins de 3 ans, ils ont transformé la théorie d'Einstein (E=mc²) en la plus terrible arme de destruction jamais créée. Certains scientifiques, comme Robert Oppenheimer, ont pleuré en voyant l'explosion du premier test atomique dans le désert du Nouveau-Mexique.\n\nLa bombe atomique change tout dans les relations entre pays. Désormais, des nations peuvent s'anéantir mutuellement en quelques minutes. Pendant la Guerre Froide, les États-Unis et l'URSS accumulent des milliers de bombes nucléaires - assez pour détruire la Terre des dizaines de fois. Cette 'destruction mutuelle assurée' crée une paix paradoxale : personne n'ose attaquer l'autre de peur d'être anéanti. Aujourd'hui encore, 9 pays possèdent des armes nucléaires, et le désarmement nucléaire reste l'un des grands défis de notre époque.",
      },
      {
        slug: "declaration-droits-homme",
        year: 1948,
        title: "La Déclaration des droits de l'homme",
        description: "Après les horreurs de la guerre, les nations du monde s'accordent sur une liste de droits fondamentaux qui appartiennent à chaque être humain.",
        content: "Le 10 décembre 1948, à Paris, les 58 pays membres des Nations Unies adoptent la Déclaration universelle des droits de l'homme. Ce texte de 30 articles proclame que tous les êtres humains, où qu'ils soient nés, quelle que soit leur couleur de peau, leur religion ou leur sexe, ont des droits fondamentaux que personne ne peut leur enlever. Droit à la vie, à la liberté, à un procès équitable, à l'éducation, à la santé... C'est la première fois dans l'histoire que tous les pays du monde s'accordent sur une telle liste.\n\nCe texte naît directement du choc des horreurs de la Seconde Guerre mondiale et de la Shoah. Les dirigeants du monde ont vu ce qui arrive quand on nie l'humanité de certaines personnes : des millions de morts. La Déclaration est portée par Eleanor Roosevelt, veuve du président américain Franklin Roosevelt, qui passe des années à convaincre les pays les plus récalcitrants de la signer. Le résultat est un texte universel qui transcende les frontières et les idéologies.\n\nAujourd'hui, la Déclaration universelle des droits de l'homme est traduite en plus de 500 langues - c'est le document le plus traduit du monde. Elle sert de base à des centaines de constitutions nationales et inspire les défenseurs des droits humains partout sur la planète. Quand Amnesty International défend des prisonniers politiques, quand des militants luttent contre la torture ou le travail des enfants, ils s'appuient sur ce texte. Ses 30 articles sont le meilleur résumé de ce que l'humanité a compris sur la dignité de chaque personne.",
      },
      {
        slug: "gagarine",
        year: 1961,
        title: "Youri Gagarine dans l'espace",
        description: "Un pilote soviétique de 27 ans devient le premier humain à voyager dans l'espace - et à voir la Terre de l'extérieur pour la première fois.",
        content: "Le 12 avril 1961, une fusée soviétique appelée Vostok 1 décolle du Kazakhstan avec à son bord un homme de 27 ans nommé Youri Gagarine. Il tourne autour de la Terre une fois en 108 minutes. Depuis l'espace, il contemple notre planète - une sphère bleue et verte suspendue dans le noir infini - et dit simplement : 'La Terre est bleue. Comme c'est magnifique !' Il rentre sain et sauf. L'humanité vient de franchir une frontière qu'elle n'avait jamais franchie : elle a quitté sa planète.\n\nCet exploit est le résultat de la course à l'espace entre les États-Unis et l'Union Soviétique. Les deux superpuissances rivalisent pour être les premières dans l'espace - par fierté nationale et pour montrer qui a la meilleure technologie. Les Soviétiques ont déjà marqué des points : ils ont lancé le premier satellite (Spoutnik, 1957) et le premier être vivant dans l'espace (la chienne Laïka, 1957). Avec Gagarine, ils remportent la palme la plus précieuse : le premier humain dans l'espace.\n\nL'exploit de Gagarine inspire des millions d'enfants à rêver de conquête spatiale. Les États-Unis, piqués au vif, investissent des milliards dans leur programme Apollo. En 1969, Neil Armstrong marche sur la Lune. Depuis Gagarine, plus de 600 humains ont voyagé dans l'espace. La Station Spatiale Internationale tourne en ce moment même au-dessus de ta tête, habitée en permanence depuis 2000. Et des missions habitées vers Mars sont planifiées pour les années 2030. Gagarine a ouvert la porte - et l'aventure ne fait que commencer.",
      },
      {
        slug: "alunissage",
        year: 1969,
        title: "Les premiers pas sur la Lune",
        description: "Neil Armstrong pose le pied sur la Lune le 21 juillet 1969 - un milliard de personnes regardent en direct ce moment historique.",
        content: "Le 20 juillet 1969, le module lunaire Eagle se pose doucement sur la surface de la Lune. Neil Armstrong ouvre la trappe, descend lentement l'échelle, et pose le pied sur le sol lunaire. Il dit alors des mots que des milliards de gens entendront : 'C'est un petit pas pour l'homme, un bond de géant pour l'humanité.' Buzz Aldrin le rejoint quelques minutes plus tard. Pendant 2h30, ils marchent sur la Lune, posent un drapeau américain et collectent des roches. Le troisième astronaute, Michael Collins, les attend en orbite.\n\nCet exploit est le résultat de 8 ans de travail acharné de 400 000 ingénieurs, techniciens et scientifiques américains, pour remplir la promesse du président Kennedy en 1961 : 'Nous irons sur la Lune avant la fin de la décennie.' Le programme Apollo a coûté l'équivalent de 160 milliards de dollars actuels. La fusée Saturn V qui les a emportés est encore aujourd'hui la plus puissante jamais construite. Trois fois, des cataclysmes auraient pu tuer les astronautes - et les sauvetages de la mission Apollo 13 (1970) montreront à quel point l'espace est dangereux.\n\nL'alunissage reste le plus grand exploit technologique de l'histoire humaine. Des civilisations qui regardaient la Lune comme une déesse ont vu des humains y marcher en moins de 10 000 ans. Depuis, 12 humains ont marché sur la Lune - tous Américains. Les roches lunaires ramenées ont révolutionné notre compréhension de la formation du système solaire. Et la NASA prépare actuellement le programme Artemis pour retourner sur la Lune dans les années 2020-2030, cette fois avec des astronautes femmes.",
      },
      {
        slug: "chute-mur-berlin",
        year: 1989,
        title: "La chute du mur de Berlin",
        description: "Le 9 novembre 1989, le mur qui divise Berlin depuis 28 ans s'effondre en direct à la télévision - et avec lui, la division de l'Europe.",
        content: "Depuis 1961, un mur de béton de 155 kilomètres divise la ville de Berlin en deux : à l'Ouest, une ville libre et prospère ; à l'Est, une ville sous régime communiste. Ce mur a été construit pour empêcher les Allemands de l'Est de fuir vers l'Ouest. Malgré les barbelés, les miradors et les chiens de garde, plus de 140 personnes ont été tuées en essayant de le franchir. Ce mur est devenu le symbole le plus concret de la division du monde entre liberté et dictature.\n\nLe 9 novembre 1989, un porte-parole du gouvernement est-allemand annonce maladroitement à la télévision que les frontières sont ouvertes 'immédiatement, sans délai'. Des milliers de Berlinois se précipitent vers les checkpoints. Les gardes, dépassés par les événements, s'écartent. Des Berlinois de l'Est et de l'Ouest se retrouvent et s'embrassent en pleurant. Ensemble, avec des marteaux, ils commencent à démolir le mur. Des scènes de joie incroyables sont filmées et diffusées dans le monde entier.\n\nLa chute du mur déclenche un effet domino : en quelques mois, les régimes communistes d'Europe de l'Est s'effondrent les uns après les autres. En 1990, l'Allemagne se réunifie. En 1991, c'est l'URSS elle-même qui se dissout. La Guerre Froide est terminée. Cette nuit du 9 novembre 1989 reste l'un des moments les plus joyeux et les plus émouvants de l'histoire récente. Elle nous rappelle que même les murs les plus solides peuvent tomber quand assez de gens décident ensemble qu'ils ne les acceptent plus.",
      },
      {
        slug: "attentat-11-septembre",
        year: 2001,
        title: "Les attentats du 11 septembre",
        description: "Quatre avions détournés frappent les États-Unis et tuent 3 000 personnes - un choc qui transforme le monde pour les décennies suivantes.",
        content: "Le 11 septembre 2001, à 8h46 du matin, un avion de ligne percute la tour nord du World Trade Center à New York. Les gens pensent à un accident. Mais 17 minutes plus tard, un second avion frappe la tour sud. Un troisième s'écrase sur le Pentagone à Washington. Un quatrième, dont les passagers tentent héroïquement de reprendre le contrôle, s'écrase dans un champ en Pennsylvanie. Ce sont des terroristes du réseau Al-Qaïda qui ont détourné ces avions pour les transformer en armes. En 2 heures, 2 977 personnes sont mortes.\n\nLes images des tours jumelles s'effondrant en direct à la télévision sont vues par un milliard de personnes. Tout le monde se souvient où il était à ce moment-là. Les États-Unis, superpuissance mondiale, viennent d'être attaqués sur leur propre sol pour la première fois depuis Pearl Harbor en 1941. La réaction américaine est immédiate : en octobre 2001, l'armée américaine envahit l'Afghanistan pour chasser les Taliban qui abritaient Al-Qaïda. En 2003, elle envahit l'Irak sous un prétexte contesté.\n\nLes conséquences du 11 septembre façonnent encore notre quotidien. À l'aéroport, tu dois enlever ta ceinture et tes chaussures à la sécurité - c'est une mesure instaurée après 2001. Nos téléphones et ordinateurs sont surveillés par les gouvernements pour traquer les terroristes. Des guerres qui ont commencé après le 11 septembre ont fait des millions de réfugiés. Vingt ans après, quand les Taliban ont repris le contrôle de l'Afghanistan en 2021, beaucoup se sont demandé si toutes ces guerres avaient servi à quelque chose.",
      },
      {
        slug: "accord-paris-climat",
        year: 2015,
        title: "L'Accord de Paris sur le climat",
        description: "195 pays s'engagent pour la première fois ensemble à lutter contre le réchauffement climatique - le plus grand défi de notre époque.",
        content: "Le 12 décembre 2015, au Bourget près de Paris, 195 pays signent un accord historique : limiter le réchauffement de la Terre à 1,5 ou 2 degrés par rapport à avant la révolution industrielle. C'est la première fois dans l'histoire que presque tous les pays du monde s'engagent ensemble sur un objectif commun pour protéger notre planète. La cheffe de la délégation française, Laurent Fabius, pleure en annonçant l'accord adopté. C'est un moment d'espoir rare dans les relations internationales.\n\nPourquoi est-ce si urgent ? Parce que depuis 150 ans, nos usines, nos voitures, nos avions et nos centrales électriques brûlent du pétrole, du charbon et du gaz, libérant du CO2 dans l'atmosphère. Ce gaz crée un 'effet de serre' qui réchauffe la planète comme une serre de jardin. La Terre s'est déjà réchauffée de 1,2 degrés - ce qui peut sembler peu, mais suffit à dérègler les saisons, faire fondre les glaciers, monter le niveau des mers et rendre les tempêtes plus violentes. Sans action, le réchauffement pourrait atteindre 3 ou 4 degrés, avec des conséquences catastrophiques.\n\nL'Accord de Paris donne de l'espoir, mais les engagements des pays ne sont pas toujours respectés. En 2018, une lycéenne suédoise de 15 ans, Greta Thunberg, commence à faire grève devant le Parlement de son pays pour réclamer une action climatique. Elle inspire le mouvement mondial des 'Fridays for Future' (Vendredis pour le Futur), avec des millions de jeunes manifestant dans le monde entier. La lutte contre le changement climatique est le grand défi de ta génération - et de nombreux jeunes comme toi décident d'en faire leur combat.",
      },
    ],
  },
];

async function main() {
  await prisma.event.deleteMany();
  await prisma.epoch.deleteMany();

  for (const epoch of data) {
    await prisma.epoch.create({
      data: {
        slug: epoch.slug,
        label: epoch.label,
        events: { create: epoch.events },
      },
    });
  }
  console.log(`Base de données alimentée : ${data.reduce((acc, e) => acc + e.events.length, 0)} événements sur ${data.length} époques ✓`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
